### PR TITLE
works with output of contigs workflow

### PR DESCRIPTION
**Pull request by mschecht**
Hi Iva!

First off, thanks for making this! It's saved me a lot of time!

I've found that I use it a lot in the context of the contigs workflow which outputs `*-contigs.db` names for contigsDBs. To adjust for this I added a conditional to the script.

Please let me know if can make this more general or any other improvements.

### CODE REVIEW

**Review by ivagljiva — APPROVED** [review]
It looks good to me, @mschecht, and I agree that it is useful to handle this case since we use this naming convention in a lot of places :) 

Thanks for the update!

**Comment by meren** [comment]
We shouldn't learn the contents of the name column from contigs db file names. I think best would be `self.meta['project_name_str']` for this.

**Comment by ivagljiva** [comment]
> I think best would be self.meta['project_name_str'] for this.

Done!

**Comment by meren** [comment]
I think it is good to go :) Thank you very much, @mschecht and @ivagljiva!

**Comment by ivagljiva** [comment]
> I think it would make more sense if is_contigs_db() returned False if dbinfo returns None. what do you think? would that break things elsewhere?

I am leaving this fix for another time :)

**Pull request merged**
