### PR TITLE
moved get_values_of_gene_level_coverage_stats_as_dict to utils

### PR DESCRIPTION
**Pull request by ShaiberAlon**
@meren, please take a look and see if this is acceptable to you. This is not urgent in any way, so no rush. Thank you!

### CODE REVIEW

**Comment by meren** [comment]
I like this, alon :) thank you very much.

**Comment by meren** [comment]
Crap. I did not accepted the PR :( Can you please resend it?

**Comment by meren** [comment]
(or directly merge to `master` :))

**Comment by ShaiberAlon** [comment]
Done. Thank you Meren.

**Pull request merged**
