### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by afuetterer**
Hi, this is my first PR to the project. Please let me know, if I missed something or touched files, that should not be changed.

This PR fixes a few typos in the code base.

### CODE REVIEW

**Comment by meren** [comment]
Dear @afuetterer, thank you SO much for this PR :) The typos in the codebase and documentation is very neglected and this PR is very much appreciated.

Would you please also include in your PR an addition to our [DEVELOPERS.yaml](https://github.com/merenlab/anvio/blob/master/anvio/data/misc/PEOPLE/DEVELOPERS.yaml)? There are enough examples in the file that you can use, and the only tricky part is a 900px by 900px avatar. More explanation is here:

https://github.com/merenlab/anvio/tree/master/anvio/data/misc/PEOPLE

If this is too much work and you're not interested in doing it, that is OK too. Just let us know by responding to this and we will merge your changes as is and close this PR :)

Thanks again,
Best wishes.

**Comment by afuetterer** [comment]
Hi @meren, thank you for your kind words.

I don't think adding myself to the developers list is necessary. The changes I contributed are trivial, they do not add functionality. So please go ahead and merge without this.

But I appreciate the offer. Maybe next time, if I add a feature or fix a bug, I would like to be mentioned. Right now, I am fine without.

**Comment by meren** [comment]
Hi @afuetterer, I am merging your PR now. But I just wanted to point out that in our view anyone who contributes *anything* to the anvi'o codebase is among the developers of the platform. There is no big or small contribution, since any contribution is infinite times larger than no contribution :) So the invitation for you to fill out a PR for the DEVELOPLERS.yaml remains open, but it is of course up to you.

I hope we run into your PRs again!


Best wishes,
Meren.

**Comment by afuetterer** [comment]
Thank you.

**Pull request merged**
