### PR TITLE
KEGG maps and reaction network

### PR DESCRIPTION
**Pull request by semiller10**
This PR expands the anvi'o metabolism toolbox, introducing `anvi-draw-kegg-pathways` for the visualization of user data in the context of KEGG's curated biochemical pathway maps.

Reaction networks generated by `anvi-reaction-network` are updated with a number of additions and fixes. A reaction network constructed from a contigs or pan database describes biochemical properties of KEGG Orthology functional annotations. It can be stored in the database and loaded into memory as a network object, containing objects representing KOs, BRITE hierarchies and categories, genes and pan gene clusters, reactions, and compounds. Networks can be manipulated (pruned, merged, etc.) and analyzed. Protein and metabolite abundances, say from proteomics and metabolomics experiments, can be loaded into a contigs database reaction network and stored in profile databases.

`anvi-draw-kegg-pathways` leverages the extensive collection of KEGG maps to explore data stored in anvi'o databases. This PR marks a first but significant step into map visualization and customization by allowing the user to show KOs from contigs and pan databases in the context of maps, as elaborated in documentation of the new program. Visualization provides immediate insight into the metabolic capabilities of single organisms (e.g., genomics), communities (e.g., metagenomics), and clades (e.g., pangenomics). The visualization strategies that have been implemented, including "map grids," enable the comparison of metabolic capabilities across organisms, communities, clades, and environments. Frameworks developed in anvi'o for handling the KEGG KGML files crucial for map customization and metabolic data in the reaction network lay the groundwork for straightforward, incremental additions enabling map visualization of the abundances of genes/transcripts/proteins/metabolites, metabolic model fluxes, sequence properties, genomic architecture, and other types of data.

### CODE REVIEW

**Comment by meren** [comment]
Thank you very much for this PR, Sam!! It is extremely exciting to see it in the main branch. I hope it will gain the attention it deserves and used by people who can demonstrate its power.

**Comment by meren** [comment]
Hey @semiller10, I have been having some hard time running `anvi-draw-kegg-pathways` due to dependency issues. 

I ended up installing three additional packages that are not mentioned in `requirements.txt` with pip:

* ReportLab
* fitz
* frontend

And even after that this was the error I was getting:

```
 anvi-draw-kegg-pathways -h
Traceback (most recent call last):
  File "/Users/meren/github/anvio/bin/anvi-draw-kegg-pathways", line 12, in <module>
    import anvio.keggmapping as keggmapping
  File "/Users/meren/github/anvio/anvio/keggmapping.py", line 7, in <module>
    import fitz
  File "/Users/meren/miniconda3/envs/anvio-dev/lib/python3.10/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
  File "/Users/meren/miniconda3/envs/anvio-dev/lib/python3.10/site-packages/frontend/__init__.py", line 1, in <module>
    from .events import *
  File "/Users/meren/miniconda3/envs/anvio-dev/lib/python3.10/site-packages/frontend/events/__init__.py", line 1, in <module>
    from .clipboard import *
  File "/Users/meren/miniconda3/envs/anvio-dev/lib/python3.10/site-packages/frontend/events/clipboard.py", line 2, in <module>
    from ..dom import Event
  File "/Users/meren/miniconda3/envs/anvio-dev/lib/python3.10/site-packages/frontend/dom.py", line 439, in <module>
    from . import dispatcher
  File "/Users/meren/miniconda3/envs/anvio-dev/lib/python3.10/site-packages/frontend/dispatcher.py", line 15, in <module>
    from . import config, server
  File "/Users/meren/miniconda3/envs/anvio-dev/lib/python3.10/site-packages/frontend/server.py", line 24, in <module>
    app.mount(config.STATIC_ROUTE, StaticFiles(directory=config.STATIC_DIRECTORY), name=config.STATIC_NAME)
  File "/Users/meren/miniconda3/envs/anvio-dev/lib/python3.10/site-packages/starlette/staticfiles.py", line 56, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'static/' does not exist
```

Figured out that to solve this one needs to uninstall the fitz and install pymupdf module instead. Which seemed to have solved the issue. So I'm adding these packages to the `requirements.txt`:

``` diff
diff --git a/requirements.txt b/requirements.txt
index ea5f34381..aad14e448 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -26,3 +26,6 @@ networkx
 biopython
 reportlab
 pulp==2.7.0
+ReportLab
+pymupdf
+frontend
```

I hope it all makes sense to you.

**Comment by semiller10** [comment]
Hi @meren, thanks for testing this right away!

It looks like `ReportLab` and `reportlab` result in the same package being installed, `4.2.2`.

`pymupdf` is imported as `fitz` so those are the same. It makes sense that this is an additional dependency, and it looks like `frontend` is required. Good catch.

**Comment by semiller10** [comment]
For the record, `reportlab` is used by `Bio.Graphics.KGML_vis.KGMLCanvas` to write PDF files, and `pymupdf` (`fitz`) is needed to load and merge PDF files in creating "map grids."

**Pull request merged**
