### PR TITLE
Profiler

### PR DESCRIPTION
**Pull request by ekiefl**
Hey @meren I incorporated your suggested changes into this branch. Please give it a look over and tell me what you think. I have a request that you re-run the IGD and verify that you still see the same number of INDELs.

Once we both like it, I will write a migration script that 

a) adds some entries to self
b) wipes the indels table if it exists
c) creates empty indels table if it doesnt exist

If you can think of anything else after reviewing these changes, let me know.

### CODE REVIEW

**Comment by meren** [comment]
Hey @ekiefl, I was just able to look at this. It all looks good to me. Thank you for catching the tables.py variables in v31_to_v32.py --it would have been a pain for older profiles for sure. I can see that you also included a migration script, too, so I guess this is ready for master.

I'm going to merge it now, re-do the IGD, and let you and @isaacfink21 know once its done.

Thank you very much!

**Comment by meren** [comment]
I was just looking at the IGD results. It certainly looks great, but I see a couple of minor issues:

- [ ] length of all instances of `DEL` is now zero:

```
sqlite3 -header -column PROFILE.db 'select * from indels where type="DEL" order by length desc limit 10;'
sample_id   split_name                    pos         pos_in_contig  corresponding_gene_call  in_noncoding_gene_call  in_coding_gene_call  base_pos_in_codon  codon_order_in_gene  cov_outlier_in_split  cov_outlier_in_contig  reference   type        sequence    length      count       coverage
----------  ----------------------------  ----------  -------------  -----------------------  ----------------------  -------------------  -----------------  -------------------  --------------------  ---------------------  ----------  ----------  ----------  ----------  ----------  ----------
Day_18      IGD_000000000011_split_00005  15258       101078         -1                       0                       0                    0                  -1                   0                     0                      T           DEL                     0           45          626
Day_18      IGD_000000000018_split_00001  1133        1133           4108                     0                       1                    1                  468                  0                     0                      T           DEL                     0           1           19
Day_18      IGD_000000000018_split_00001  4908        4908           4111                     0                       1                    1                  373                  0                     0                      A           DEL                     0           1           17
Day_18      IGD_000000000018_split_00002  5666        25693          4132                     0                       1                    1                  49                   0                     0                      T           DEL                     0           1           17
Day_18      IGD_000000000018_split_00002  15641       35668          -1                       0                       0                    0                  -1                   1                     1                      T           DEL                     0           2           28
Day_18      IGD_000000000018_split_00002  16216       36243          -1                       0                       0                    0                  -1                   0                     0                      A           DEL                     0           1           17
Day_18      IGD_000000000018_split_00003  7017        48710          4150                     0                       1                    3                  547                  0                     0                      C           DEL                     0           1           13
Day_18      IGD_000000000018_split_00003  7029        48722          4150                     0                       1                    3                  551                  0                     0                      T           DEL                     0           1           16
Day_18      IGD_000000000018_split_00003  13668       55361          4158                     0                       1                    2                  4                    0                     0                      T           DEL                     0           1           14
Day_18      IGD_000000000018_split_00004  4391        67244          4166                     0                       1                    2                  1409                 0                     0                      A           DEL                     0           1           14
```

- [ ] in some cases of type deletion, the `count` is larger than `coverage` (and sometimes QUITE a lot --see the last two columns):

```
sqlite3 -header -column PROFILE.db 'select * from indels where count > coverage order by count desc limit 10;'
sample_id   split_name                    pos         pos_in_contig  corresponding_gene_call  in_noncoding_gene_call  in_coding_gene_call  base_pos_in_codon  codon_order_in_gene  cov_outlier_in_split  cov_outlier_in_contig  reference   type        sequence    length      count       coverage
----------  ----------------------------  ----------  -------------  -----------------------  ----------------------  -------------------  -----------------  -------------------  --------------------  ---------------------  ----------  ----------  ----------  ----------  ----------  ----------
Day_17A     IGD_000000001292_split_00001  740         740            24191                    0                       1                    2                  22                   0                     0                      G           DEL                     0           931         418
Day_17B     IGD_000000002033_split_00001  1353        1353           -1                       0                       0                    0                  -1                   1                     1                      T           DEL                     0           359         260
Day_18      IGD_000000002033_split_00001  1353        1353           -1                       0                       0                    0                  -1                   1                     1                      T           DEL                     0           336         248
Day_16      IGD_000000002033_split_00001  1353        1353           -1                       0                       0                    0                  -1                   1                     1                      T           DEL                     0           330         326
Day_22A     IGD_000000002033_split_00001  1353        1353           -1                       0                       0                    0                  -1                   1                     1                      T           DEL                     0           311         293
Day_19      IGD_000000002033_split_00001  1353        1353           -1                       0                       0                    0                  -1                   1                     1                      T           DEL                     0           267         206
Day_24      IGD_000000002033_split_00001  1353        1353           -1                       0                       0                    0                  -1                   1                     1                      T           DEL                     0           257         199
Day_24      IGD_000000000045_split_00005  20245       105220         -1                       0                       0                    0                  -1                   0                     0                      A           DEL                     0           208         135
Day_17B     IGD_000000001292_split_00001  664         664            -1                       0                       0                    0                  -1                   0                     0                      C           DEL                     0           184         169
Day_23      IGD_000000000045_split_00005  20245       105220         -1                       0                       0                    0                  -1                   0                     0                      A           DEL                     0           174         117
```

**Comment by ekiefl** [comment]
> indels are length 0

Ok great catch. I will fix that.

> count exceeds coverage

It could be a mistake, however there is nothing theoretically wrong with this. If you have a 500X covered genome and the environment has an unanimous 1nt deletion compared to reference, the coverage would be 0 and the count 500.

So I guess I'm curious what the coverage is a few positions to the left of that first position in the table, where the count is 900 and the coverage 400. I would expect it to be around 1300.

To me it is reassuring we do not see insertions with count greater than coverage.

**Comment by meren** [comment]
> So I guess I'm curious what the coverage is a few positions to the left of that first position in the table, where the count is 900 and the coverage 400. I would expect it to be around 1300.

This is tricky, and I am not sure how to address it 100%.

In my original message I had suggested that perhaps we should take the average of nucleotide positions next to the deletion site to have an idea about coverage (unless deletion is the first or the last base in the contig, in which case we take only one side). But then this doesn't sound 100% right, either.

**Comment by ekiefl** [comment]
> In my original message I had suggested that perhaps we should take the average of nucleotide positions next to the deletion site to have an idea about coverage

I am confused. I think that would be misleading. What is currently being reported for `coverage` is the coverage of the nucleotide position the deletion is overtop. I can't imagine it being anything else. So I guess I'm not sure what is troubling.

Is it that `--min-indel-fraction` is skewed because deletions counts take away from coverage, but insertion counts do not? I'm not worried about this because realistic a `--min-indel-fraction` is so small that `count/coverage` is approximately `count/(coverage+count)`. These 2 metrics only have a large distance from each other _after_ `--min-indel-fraction` has already been met.

**Comment by meren** [comment]
Fair enough :) I am sold.

**Comment by ekiefl** [comment]
Ok I did something that makes more sense.

Currently, insertion coverages are just the position's coverage left of the insertion. But it is equally important to consider the position's coverage right of the insertion. So the reported coverage is the average of the left and right positions. If the left-hand position is the last position in the split, then the reported coverage is the coverage of the left-handed position.

For deletions, the reported coverage is the average of all the NT coverages that the deletion is over. Before we would report the coverage of only the first position in the deletion, even if the deletion was 50 NTs. 

Coverages are now reported as floats.

Can you please run the IGD one final time? The changes have been merged.

**Comment by meren** [comment]
We should also include this information in whichever file feels most appropriate so there is a resource for people to learn how these coverages are computed:

https://github.com/merenlab/anvio/tree/master/anvio/docs

I'm redoing the IGD now :)

**Comment by meren** [comment]
All, done and it all looks good. @isaacfink21, please use the data pack here; in which the directory `NEW` includes results from the current `master`:

https://www.dropbox.com/s/p5w0ila6yo897xo/INFANT-GUT.tar.gz

Thank you both!

**Pull request merged**
