### PR TITLE
Use nest_legacy if tidyr ver >= 1, nest otherwise

### PR DESCRIPTION
**Pull request by mooreryan**
`tidyr` uses new syntax for `nest` as of version `1.0.0` (see [here](https://tidyr.tidyverse.org/reference/nest.html#new-syntax)).  

This bug fix will check to see which version of `tidyr` that the user has installed/loaded.  If it is `>= 1`, then use the `nest_legacy` function, otherwise, just continue on with the `nest` function as written.

Rather than rewrite any of the code that is there, this should work for users of both the old and the new libraries.

(This should address https://github.com/merenlab/anvio/issues/1248)

### CODE REVIEW

**Comment by mooreryan** [comment]
I tested that this works using the input file from this comment: https://github.com/merenlab/anvio/issues/1248#issuecomment-538597210, with both `tidyr` versions `0.8.3` and `1.0.0`.

**Comment by mooreryan** [comment]
I requested a review from @meren as this approach is a bit "hackish"....

**Comment by meren** [comment]
I think this is a great solution, @mooreryan :) thank you very much again.

**Comment by ShaiberAlon** [comment]
Thank you very much for getting to the bottom of this and solving it @mooreryan!

**Pull request merged**
