### PR TITLE
Undo & Redo implementation for the interactive interface

### PR DESCRIPTION
**Pull request by ozcan**
`Cmd/Ctrl + Z` for undo.
`Cmd/Ctrl + Shift + Z` for redo.

Currently keeps track of:
 - selections
 - bin add/delete
 - bin color changes

### CODE REVIEW

**Comment by meren** [comment]
This is amazing :) I am testing it now, an the first thing I realized is that removal of bins (as a whole or individually) by clicking on the trash bin icon no longer works:

image

:)

**Comment by meren** [comment]
Another thing I realized:

Make a selection:

image

Make bigger selection:

image

CMD+Z:

image

It is all gone, instead of going to the smaller selection.

**Comment by ozcan** [comment]
Good catch @meren, I am looking into this.

**Comment by ozcan** [comment]
Both fixed now @meren, thank you for testing :)

**Comment by meren** [comment]
It works like magic now 😍

**Pull request merged**
