### PR TITLE
Updating the databases for anvi'o SCG taxonomy

### PR DESCRIPTION
**Pull request by meren**
Not only updating the databases, but also the way we're dealing with them.

More about this in #2211.

### CODE REVIEW

**Comment by mschecht** [comment]
Ran this to confirm `metagenome-mode` is working correctly with [this commit](https://github.com/merenlab/anvio/pull/2210/commits/9eb48e5470727b0e229f6a4406a7a7ea8b61e197):

```bash
cd INFANT-GUT-TUTORIAL/additional-files/pangenomics

# Test on single contigs-db - This should throw an error because they don't have the new data
$ anvi-estimate-scg-taxonomy -c external-genomes/Enterococcus_faecalis_6255.db   --metagenome-mode --scg-name-for-metagenome-mode Ribosomal_S15 -o asdf
Config Error: The SCG taxonomy database version on your computer (GTDB: v214.1; Anvi'o: v1) is
              different than the SCG taxonomy database version to populate your contigs
              database (v95). Please re-run the program `anvi-run-scg-taxonomy` on your
              contigs-db.


# Test is on multiple contigs-dbs
head -n 4 external-genomes.txt > external-genomes-small.txt

# This should throw an error
$ anvi-estimate-scg-taxonomy -M external-genomes-small.txt  --metagenome-mode --scg-name-for-metagenome-mode Ribosomal_S15 -O asdf
Config Error: The SCG taxonomy database version on your computer (GTDB: v214.1; Anvi'o: v1) is
              different than the SCG taxonomy database version to populate your contigs
              database (v95). Please re-run the program `anvi-run-scg-taxonomy` on your
              contigs-db.

# update one of the contigs-dbs and see what happens
anvi-run-scg-taxonomy -c external-genomes/Enterococcus_faecalis_6240.db -T 5

# Still catches the error woohoo! :)
$ anvi-estimate-scg-taxonomy -M external-genomes-small.txt  --metagenome-mode --scg-name-for-metagenome-mode Ribosomal_S15 -O asdf
Config Error: The SCG taxonomy database version on your computer (GTDB: v214.1; Anvi'o: v1) is
              different than the SCG taxonomy database version to populate your contigs
              database (v95). Please re-run the program `anvi-run-scg-taxonomy` on your
              contigs-db.

# Update them all and see what happens

for genome in ` tail -n +2 external-genomes-small.txt | cut -f 2`; do anvi-run-scg-taxonomy -c $genome -T 6; done

$ anvi-estimate-scg-taxonomy -M external-genomes-small.txt  --metagenome-mode --scg-name-for-metagenome-mode Ribosomal_S15 -O asdf
Num metagenomes ..............................: 3
Taxonomic level of interest ..................: (None specified by the user, so 'all levels')
Output file prefix ...........................: asdf
Output in matrix format ......................: False
Output raw data ..............................: False
SCG coverages will be computed? ..............: False
SCG [chosen by the user] .....................: Ribosomal_S15

* Your metagenome file DOES NOT contain profile databases, but you asked anvi'o to
  estimate SCG taxonomy in metagenome mode. So be it. SCG name is set to
  Ribosomal_S15.

Long-format output ...........................: asdf-LONG-FORMAT.txt
# and it works!
```

**Comment by ivagljiva** [comment]
I also tested on the Infant Gut Dataset (the main assembly in metagenome mode), as well as one of my single contigs db test files, and can confirm it works perfectly :)

**Review by ivagljiva — APPROVED** [review]
Looks great @meren !

**Comment by ivagljiva** [comment]
See 4eab829195700e3c4fe6964b876151a778b33344 and 06a5769a0478ef8e7003c073daaa36660039fd75 for the fixes

**Pull request merged**
