### PR TITLE
added developer info

### PR DESCRIPTION
**Pull request by nick-youngblut**
Added my info to DEVELOPERS.yaml

### CODE REVIEW

**Comment by meren** [comment]
Hey @nick-youngblut, this is missing an `avatar` entry and a 900x900px file into the `AVATARS` directory.

By the way, totally irrelevant note, I've been watching to CI to go through all the checks. It seems to be working very nicely.

**Comment by meren** [comment]
(although, it will be an overkill for every commit and/or PR, and I am wondering if there is a more mindful / more precise way to trigger these checks).

**Comment by meren** [comment]
Thanks!

**Comment by nick-youngblut** [comment]
>this is missing an avatar entry and a 900x900px file into the AVATARS directory.

I was lazy and didn't add it, but now I've included it. 

> I've been watching to CI to go through all the checks. It seems to be working very nicely.

🎉 

> With the current setup, it will take 6 minutes per commit, and that will quickly add with our rate of development to hundreds of dollars every month

You are paying for CI? Generally, it's [free for limited resource-CI](https://github.com/pricing)

**Comment by meren** [comment]
> You are paying for CI? Generally, it's [free for limited resource-CI](https://github.com/pricing)

I hadn't realized that it is free for public repos! 😂 Never mind.

**Comment by nick-youngblut** [comment]
>Although, it will be an overkill for every commit and/or PR, and I am wondering if there is a more mindful / more precise way to trigger these checks.

Check out [this thread](https://stackoverflow.com/questions/70377390/is-there-any-way-to-trigger-a-specific-github-action-workflow-by-commit-message)

**Pull request merged**
