### PR TITLE
Reformat BAM files created prior to `anvi-script-reformat-fasta`

### PR DESCRIPTION
**Pull request by telatin**
*Ciao pips! I recently joined the Anvi'O fanclub thanks to EBAME 8 :)*

When a user generated an assembly and backmapped reads against it, but then want to import everything on Anvi'o, it can be the case that the contigs will contain names unwanted by Anvi'o.

`anvi-script-reformat-fasta` can:
* rename the contigs (producing the new FASTA file)
* generate a conversion TSV file (here referred to as `reformat-report`)

This PR proposes to add a new `anvi-script-reformat-bam` that takes as input:
1) A BAM file generated against the initial assembly
2) The `reformat-report` produced by `anvi-script-reformat-fasta`

And produces a:
1) New BAM file with converted references

[For a small test dataset and documentation see [telatin/anvi-script-reformat-bams](https://github.com/telatin/anvi-script-reformat-bams#readme)]

📖  I tried drafting a md documentation page, I would appreciate help there, thanks!

### CODE REVIEW

**Comment by meren** [comment]
Dear @telatin, thank you very much for this PR! Everything looks great apart from a few minor issues I see with the docs (such as a `%(contigs-fasta)` instead of `%(contigs-fasta)s`) :) Please run the following command in your branch to make sure you don't see any errors (you can run it before fixing anything so hopefully this program can help you recognize the issue conveniently):

```
anvi-script-gen-help-pages -o TEST
```

(this is the exact command anvio.org will run to update the online docs :))


Best wishes,

**Comment by meren** [comment]
Thank you very much, @telatin :) It is now in the main branch, and the docs at https://anvio.org/help/ will sync soon.

**Comment by meren** [comment]
Hey @telatin, I've made a few changes at #2168. I tried to explain my reasoning behind those changes in each commit (it is much more useful to look at them one by one than looking at the overall changes all at once).

I hope they're agreeable to you.

**Comment by meren** [comment]
Apologies for sending things one by one. There is also #2169 that contains a few relevant follow-up changes here.

**Comment by ivagljiva** [comment]
Beautiful work 🥲

**Pull request merged**
