### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by metehaansever**
**PLESE DO NOT MERGE**
This PR to see the latest changes before writing to the master.

### CODE REVIEW

**Comment by meren** [comment]
I just realized that clicking on "Generate a static summary page" button while working with a pangenomes result in the following error:

image

Same occurs with the regular interactive (i.e., with infant gut dataset).

At the root of this issue lies the broken symlinks that look like this,

image

which obviously only work for *your* computer, instead of relative ones that would work for everyone :) I hope you can fix the symlinks when you have a chance.

**Comment by metehaansever** [comment]
> I just realized that clicking on "Generate a static summary page" button while working with a pangenomes result in the following error:
> 
> image
> Same occurs with the regular interactive (i.e., with infant gut dataset).
> 
> At the root of this issue lies the broken symlinks that look like this,
> 
> image
> which obviously only work for _your_ computer, instead of relative ones that would work for everyone :) I hope you can fix the symlinks when you have a chance.

Thank you for catching that @meren !! i'll fix it :+1:

**Comment by meren** [comment]
Thanks for 28721b5ac763da7beba2ca260b94b60ad59e4eaa, Mete, but there are more:

```
/Users/meren/github/anvio/anvio/data/static/content/pics/logo-simple.png -> /home/msever/github/anvio/anvio/data/interactive/images/logo-simple.png
```

Please make sure `anvi-summarize` works for metagenomes and pangenomes.

**Comment by meren** [comment]
I also can see that bootstrap glyphicons no longer render. I'm not sure why :/

image

**Comment by meren** [comment]
Another point: While going through which new files this PR brings into main, I realized we have a new directory for Roboto fonts (where we literally add roboto fonts to anvi'o codebase). But when I checkout the repository from https://github.com/googlefonts/roboto, the repo seems to have all the files we need:

```
./src/hinted/Roboto-Medium.ttf
./src/hinted/Roboto-Light.ttf
./src/hinted/RobotoCondensed-Bold.ttf
./src/hinted/RobotoCondensed-Light.ttf
./src/hinted/Roboto-Regular.ttf
./src/hinted/Roboto-MediumItalic.ttf
./src/hinted/RobotoCondensed-Italic.ttf
./src/hinted/RobotoCondensed-BoldItalic.ttf
./src/hinted/RobotoCondensed-LightItalic.ttf
./src/hinted/Roboto-ThinItalic.ttf
./src/hinted/RobotoCondensed-Regular.ttf
./src/hinted/Roboto-BoldItalic.ttf
./src/hinted/Roboto-LightItalic.ttf
./src/hinted/Roboto-Italic.ttf
./src/hinted/Roboto-BlackItalic.ttf
./src/hinted/Roboto-Bold.ttf
./src/hinted/Roboto-Thin.ttf
./src/hinted/Roboto-Black.ttf
```

Would it not have been better to add roboto as a submodule like everything else under lib?

**Comment by metehaansever** [comment]
> I also can see that bootstrap glyphicons no longer render. I'm not sure why :/
> 
> image

I fixed that :)

**Comment by metehaansever** [comment]
> Another point: While going through which new files this PR brings into main, I realized we have a new directory for Roboto fonts (where we literally add roboto fonts to anvi'o codebase). But when I checkout the repository from https://github.com/googlefonts/roboto, the repo seems to have all the files we need:
> 
> ```
> ./src/hinted/Roboto-Medium.ttf
> ./src/hinted/Roboto-Light.ttf
> ./src/hinted/RobotoCondensed-Bold.ttf
> ./src/hinted/RobotoCondensed-Light.ttf
> ./src/hinted/Roboto-Regular.ttf
> ./src/hinted/Roboto-MediumItalic.ttf
> ./src/hinted/RobotoCondensed-Italic.ttf
> ./src/hinted/RobotoCondensed-BoldItalic.ttf
> ./src/hinted/RobotoCondensed-LightItalic.ttf
> ./src/hinted/Roboto-ThinItalic.ttf
> ./src/hinted/RobotoCondensed-Regular.ttf
> ./src/hinted/Roboto-BoldItalic.ttf
> ./src/hinted/Roboto-LightItalic.ttf
> ./src/hinted/Roboto-Italic.ttf
> ./src/hinted/Roboto-BlackItalic.ttf
> ./src/hinted/Roboto-Bold.ttf
> ./src/hinted/Roboto-Thin.ttf
> ./src/hinted/Roboto-Black.ttf
> ```
> 
> Would it not have been better to add roboto as a submodule like everything else under lib?

That's correct Meren, i did that to be sure we will have Roboto font for static pages. But this way would be better for sure.

**Comment by metehaansever** [comment]
I removed fonts/roboto directory and create submodule for Roboto font. Also i created symlink for static pages. @meren

**Pull request merged**
