### PR TITLE
Phylo workflow

### PR DESCRIPTION
**Pull request by ShaiberAlon**
Added a phylogenomic workflow that accepts either internal genomes file or external genomes file or both and uses trimal, and iqtree.

In addition also addressed #926.

I left the default `min_len` for `anvi-script-reformat-fasta` to zero. The user can do what they want.

### CODE REVIEW

**Comment by ekiefl** [comment]
Wow nice work Alon! I sense this will be hugely useful for people.

**Comment by ShaiberAlon** [comment]
Thanks Evan!

**Comment by meren** [comment]
Wow. I'm just seeing this, Alon. This is great!

**Comment by meren** [comment]
Wow. I'm just seeing this, Alon. This is great!

**Comment by ShaiberAlon** [comment]
Thanks :-)

**Pull request merged**
