### PR TITLE
Display author names in help pages

### PR DESCRIPTION
**Pull request by meren**
This PR enables anvi'o help pages to include author names associated with anvi'o programs. It has been a struggle to credit those who develop tools into anvi'o, and this is one of many steps towards the right direction.

The technical framework here includes (1) a YAML file that describe every anvi'o author who implemented a program, or have made significant contributions to the underlying code for that program to operate, and (2) its linkage to the `AnvioDocs` class.

To make things a bit more unified, in each anvi'o program or script, I replaced every `__maintainer__` tag with `__authors__` tag, where the following lines,

```
__maintainer__ = "A. Murat Eren"
__email__ = "a.murat.eren@gmail.com"
```

started to look like this one,

```
__authors__ = [meren, ekielf]
```

So multiple can be listed with their Github username (in the long run will make things much easier). The YAML file contains all the other information for any author mentioned in any program:

```yaml
(...)

- github: ekiefl
  name: Evan Kiefl
  twitter: ecneicScience
  linkedin: evan-kiefl-825985b7
  orcid: 0000-0002-6473-0921
  email: kiefl.evan@gmail.com
  avatar: ekiefl.jpg
  bio: "I am interested in uncovering how single nucleotide variants map to functional variation in the genes of naturally-occuring microbial populations."
  affiliations:
    - title: Graduate Student
      inst: The Biophysical Sciences Program at the University of Chicago
      inst_link: http://biophysics.uchicago.edu/

- github: mschecht
  name: Matthew Schechter
  email: mschechter@uchicago.edu
  avatar: mschecht.jpg
  linkedin: matthewschechter
  orcid: 0000-0002-8435-3203
  twitter: mschecht_bio
  bio: "I am interested in combining comparative genomics and environmental metagenomics to identify genetic determinants of fitness in microbial populations in the human gut and ocean microbiome."
  affiliations:
    - title: Graduate Student
      inst: Committee on Microbiology at the University of Chicago
      inst_link: https://biomedsciences.uchicago.edu/page/microbiology

(...)
```

Which are then rendered by the program `anvi-script-gen-help-pages` to be further rendered by any `jekyll`, which, at the end looks like this:

image

or like this:

image

Adding a new name to a page is as easy as adding the github username of anyone who needs to be included as an author of an anvi'o program to its source code.

### CODE REVIEW

**Review by ivagljiva — APPROVED** [review]
This is beautiful @meren :)

**Comment by meren** [comment]
Latest commits also add author information (a tinier version that is) to the programs index page:

image

image

The images are hyperlinked to Twitter, LinkedIn, or GitHub pages (in that order of preference, open to discussion).

**Comment by ekiefl** [comment]
This is a great step in the right direction. I like how credit is shown in both the overview page (as little icons) as well as full ID cards within each program.

I think two troubling aspects moving forward will be defining what is significant enough to count as being adding to `__authors__`, and how we will maintain these author lists over time as the underlying codebase is overhauled.

To help create parameters that define authorship, I took a look at my contributions to programs that I am not currently an author on. They are ordered subjectively from most to least "deserving". Perhaps we can shape some criteria from this set of examples. By the way, I don't mean for this to be so self-centered, but I obviously know my contributions best so it's what I have focused exclusively on.

`anvi-export-gene-calls`
- Implemented the requirement that a gene caller must be specified (https://github.com/merenlab/anvio/commit/6a336b3fe368785174f66d5b3776c39fd5cfb992)
- Implemented default behavior that amino acid sequences are to be reported as an additional column (requirement to ensure the same contigs database is generated by using `export-gene-calls` followed by `anvi-gen-contigs-database --external`), and the ability to skip amino acid sequencing reporting (https://github.com/merenlab/anvio/commit/6a336b3fe368785174f66d5b3776c39fd5cfb992)
- Notes: contributed significantly to intellectual framework and design decisions of underlying code base, git blame shows a significant fraction of lines are mine

`anvi-init-bam`
- Used to be single-threaded, however for very large BAM files this can take hours. Upon the request of a user, I implemented the ability to specify multiple threads (https://github.com/merenlab/anvio/commit/2c5fd15f85a5f2343821e103331c05932c1b5e64)
- Notes: important change, but not very intellectual

`anvi-script-reformat-fasta`
- Implemented the `--seq-type` flag to replace bad characters in FASTA files with `N` for nucleotides, `X` for amino acids, etc (https://github.com/merenlab/anvio/commit/7619e433b02a632dd49612366c2be3ac225fc8ce). Fixes issues users were having when trying to map to reads to contigs databases containing bizarre sequence characters
- Implemented ability to filter based on read ids you want to keep (https://github.com/merenlab/anvio/commit/f3073abf4a218697ace5f4cb2a8f046e657d5147)
- Notes: First commit fixes fundamental anvi'o issue (therefore intellectual), second commit is just a convenience feature

`anvi-get-codon-frequencies`
- Added the `--collapse-genes` feature so that a single value is reported for each codon (https://github.com/merenlab/anvio/pull/1756)
- Notes: convenience feature

`anvi-delete-hmms`
- identified this issue (https://github.com/merenlab/anvio/issues/1366) with `anvi-delete-hmms`, and implemented this PR (https://github.com/merenlab/anvio/pull/1368) to fix it
- Notes: Fix to a moderately important bug

`anvi-run-workflow`
- Notes: A spattering of commits for adding or removing variables from the workflow, typos, etc.

For each case, I added a "Notes" section in an attempt to broadly describe the importance of the contribution. I think it's pretty obvious that my contributions to `anvi-export-gene-calls` deserve authorship and probably just an oversight. Poor @meren went through hundreds of files to attribute authorship and it is expected that some things will slip through the cracks during the first pass. Let me know if you think otherwise @meren.

In an attempt to take the lead in defining authorship criteria, I think all of these other listed contributions do not quite qualify for authorship. Why? I think a common trend in these examples is the addition of a convenience flag with no changes to the underlying code or intellectual design. I don't think this is enough. Instead, I think there should be evidence of code being written that is an integral part of the program, how it is designed, and how it performs. The contribution should take place in either in the program itself, or in the underlying codebase. For example, I have barely touched the program `anvi-profile`, yet I am an undisputed king of `anvi-profile` due to my contributions to the underlying codebase.

I would encourage all developers to either accept or reject my notions of authorship based on the review of their own contributions to anvi'o and how it is reflected in the current state of the `__authors__` tags.

**Comment by meren** [comment]
Thank you for your comment, @ekiefl.

> I think it's pretty obvious that my contributions to `anvi-export-gene-calls` deserve authorship and probably just an oversight.

Indeed. I didn't do anything more than replacing what was defined in the `__maintainer__`  and `__credits__` tags with matching GitHub usernames under the new `__authors__` tag. So I knew things were going to fall over the cracks with this initial attempt, but my purpose was to create a framework so we could fill it in with more realistic data and then try to keep it up to date.

I was planning to write a short post on this new feature this weekend and ask everyone to go through and think about their contributions and add their names. What you did would have been a very appropriate and desired response to that: "_I have invested into these programs and this is how_". I think going forward the best solution will be to add any name to _any_ program, and send a PR with a similar information you have shared here so it could be the "exemplary" way of doing this.

But more broadly there are few important things to think about.

First, what qualifies authorship? I think it is best to be inclusive. Obvious contributions that deserve authorship, in my opinion, include redesigning or improving the underlying library, fixing bugs, or adding new flags or functionality. But there are cases that deserve authorship even when there is no code evidence like the ones I listed. As I said, I am on the side of inclusivity, but even then I am not sure how we will be able to maintain a fair strategy. I think the tricky final decisions will fall on the shoulders of the anvi'o project leaders and they can always discuss among one another to decide what is fair. But there are some obvious ones, as long as we can remember them: for instance, I think Tom should be listed under `anvi-refine`. He hasn't changed the code of the program or any of the underlying libraries, but he did make significant intellectual contributions to the program and its function, and he is not around GitHub to raise his voice. There will be other cases like this, too. So how do we recognize such contributions and consider for authorship is also a difficult one to address. There is a reason you focused on your own contributions: you know them the best. But how about the contributions of those who are not around anymore to remember? This bothers me, too. My answer is that we can do our best, and admit that we will never have a complete list. After all anything we do on this will be an infinitely large improvement in comparison to what we have been doing so far. So there is that.

Then there are those of us who have been working on anvi'o for a long time which puts them on a different place compared to those that joined the development recently. For instance, I can have an accident that destroys my frontal lob and after that I may start arguing that I have intellectually contributed to everything in anvi'o so I must be recognized for every single program in it. How do we stop this from happening _is_ an important question, too. In other words, where do we draw the line?

These are the kinds of questions that stop open-source projects from going fully open and community-owned. And there is a reason why most of the open-source projects that are successful enough to be still around have these benevolent dictators that _draw every line_ for decades. I'm sure we will figure these things out and be better.

The primary reason I decided to work on this now was to make sure @ivagljiva could reference https://merenlab.org/m/anvi-estimate-metabolism from a write up, or you could reference https://merenlab.org/m/anvi-setup-interacdome and people would immediately recognize your name on the page. But a much better way to do this certainly would be to change this data structure,

``` python
__authors__: [meren, ekiefl]
```

to this more talented and comprehensive version of it:

``` python
__authors__: [(meren, 'implemented the initial draft', '7dd26bb503b7bdd99b91afd60a00362bce449066'),
              (ekiefl, 'parallelized the program', 'pr_number'),
              (ekiefl, 'added flags `--xxx` and `--yyy`', 'commit_id'),
              (meren, 'added documentation', 'pr_number')]
```

I think a change to a data structure like the one above not only would make the order of names less relevant, but also solve the problem of not losing track of names as the codebase evolves. I wish we could do this automatically, but git blame of the final file is not very helpful (someone goes into a file and changes every four spaces to a TAB or something of that sorts changes the status of the file) and number of people committed to each file is not always relevant (I often change copyleft date or header variables automatically, so my GitHub ID is associated even with files to which I didn't contribute anything tangible).

The best way to do it is to go through the history of files under `anvio/*py`, and add significant changes to programs that benefit from those changes (i.e., a user-centric impact of changes). But then this is quite a significant amount of work for people to fill in, and doing it half ass is dangerous (exhibit A). Of course it could have been much easier if we had started like this. If you or anyone else are willing to do it for everyone, I would be more than happy to work on the front-end to make things look neat and beautiful (such as having an authors page, listing names and all the programs they have contributed to as separate pages and so on -- like an online anvi'o CV :p). Otherwise it will have to wait until we have a historian who is interested in the history of programs to take on this project.

In the meantime, it is perfectly OK to think broadly, in an inclusive manner, and add people (or your name) in any program you recognize.

Again, the initial form this framework was never meant to be its final form. This was largely an infrastructure work to continue implementing technical needs for this grand plan I have for the anvi'o web domain change.

**Comment by ekiefl** [comment]
To summarize our discussion offline, this is a great start and there are certainly aforementioned ways to improve it. Erring on the side of inclusivity is always a good idea. Hopefully word will spread once the post is released and contributors or people on their behalf add their contributions to the `__author__` tags.

**Pull request merged**
