### PR TITLE
Add split coverages script

### PR DESCRIPTION
**Pull request by mooreryan**
References #1170.

Basically it's just a CLI wrapper that (should) handle user input in a nice way for @meren's RStudio code in the issue.  

I didn't add any other visualization strategies in case this script wasn't exactly what you're looking for.

Hopefully this helps!

### CODE REVIEW

**Comment by mooreryan** [comment]
Just updated the script.  Uploaded some test files as well so you can see how it works.

[test_files.tar.gz](https://github.com/merenlab/anvio/files/3288404/test_files.tar.gz)

Preview of the `--help` banner.

```
./sandbox/anvi-script-visualize-split-coverages -h
Usage: ./sandbox/anvi-script-visualize-split-coverages -i infile.txt -o coverage_graphs.pdf [-s sample_data.txt] [-w chart_width] [-c chart_height] [-t chart_type] [-m max_coverage]

Description:
  Generate PDF image of coverage for splits across multiple samples.

  - The input file required for this script is the output of the program anvi-get-split-coverages.

  - Any color that is not included in `colors()` or a valid hex code #00FF00 will be changed to 'black'.

  - Current options for --chart-type include: 'area', 'line'

Options:
	-i INFILE, --infile=INFILE
		Path to infile (i.e., output of anvi-get-split-coverages)

	-s SAMPLE-DATA, --sample-data=SAMPLE-DATA
		Path to additional data file

	-o OUTFILE, --outfile=OUTFILE
		Path to outfile

	-w WHOLE-CHART-WIDTH, --whole-chart-width=WHOLE-CHART-WIDTH
		Width of the whole chart [default 10]

	-c INDIVIDUAL-CHART-HEIGHT, --individual-chart-height=INDIVIDUAL-CHART-HEIGHT
		Height of each individual coverage chart [default 2]

	-t CHART-TYPE, --chart-type=CHART-TYPE
		What type of chart do you want? [default area]

	-m MAX-COVERAGE, --max-coverage=MAX-COVERAGE
		Max coverage.  Any value g.t. this will be capped at this value. [default 1000]

	-h, --help
		Show this help message and exit
```
If this is closer to what you're looking for, I can write better documentation for all the functions.

**Comment by mooreryan** [comment]
Pretty much everything is wrapped in a function now that takes the parsed options and the validated user data.

Adding new plotting functions just needs to write a new function with this sort of signature

```
my_flot_fn <- function(dat, opts)
```
that outputs a ggplot object.  For now, I've included the area chart and a line chart just to show that it can be done.  More could be added later.

Other stuff...

* Parsing options is also pretty modular.
* Sample data (additional data file) gets joined on `sample_name` to the original data so that file could also be extended and cool things done with ggplot.

**Comment by meren** [comment]
Hey Ryan,

This is quite advanced compared to the first commit! Thank you very much. I think we should go with this script and make sure it is included in the next release :) I updated the other message so no one else is putting in effort into developing something similar in parallel.

I've been playing with it, and things look good in general. However, there is one problem I wanted to give you an opportunity think about addressing if you still have energy and interest.

As you know, once we start dealing with real-world data beyond mock examples things that perform seemingly well start to fall apart terribly :) In this case, it happens when ggplot tries to plot all those points point by point. I am sure one could smooth the data a bit first in R. I am sure there are ways to compress large arrays with adjustable levels of loss of resolution. So one way to make your lovely program something that can be scaled to even large datasets is to perhaps think about that kind of optimization (if there are more than 1,000 data points per sample it could automatically kick in with a default, warn the user, and tell them if it is taking too long they can always increase some alpha to use smaller number of data points to visualize the coverage.

If you would like to play with that, here are two examples. This one has lots and lots of zeros:

[SPLIT-COV-TEST-01.txt.gz](https://github.com/merenlab/anvio/files/3288645/SPLIT-COV-TEST-01.txt.gz)

And another one that is filled with ups and downs:

[SPLIT-COV-TEST-02.txt.gz](https://github.com/merenlab/anvio/files/3288646/SPLIT-COV-TEST-02.txt.gz)

If you no longer have time for this adventure, let me know :) I will merge the PR and close it happily.


Best,

**Comment by mooreryan** [comment]
[pdfs.tar.gz](https://github.com/merenlab/anvio/files/3291815/pdfs.tar.gz)

Thanks for the comments.  Good point on the bigger datasets...I added a compression method.

It uses running medians (window size can be set by the user or the program can calculate it automatically based on data size) to first smooth the data, then subsets the original data by only plotting nucleotide positions that evenly divide the window size (plus the final position so the whole contig gets plotted).

On that first test data set, the area charts drop from taking ~3.5 minutes to about ~10 seconds, which is nice.  I attached a bunch of PDFs and a shell script to generate them so you can see how the things look with compression.

**Comment by mooreryan** [comment]
I also added some instructions at the top for anyone who want to add more plotting methods in the future.

**Comment by meren** [comment]
Brilliant! :) Thank you very much, @mooreryan, this will be such a great help for many. I am now merging this pull request to `master`, and your script will be in anvi'o `v6` we wish to release soon.

I will write a short blog post and describe the utility and features of `anvi-script-visualize-split-coverages` --of course unless you want to do it yourself :) If you would rather do it yourself, you can do it anywhere, including our blog, and I would happily link it from our online documentation whenever appropriate. We have been very lucky to have [guest contributions](http://merenlab.org/people/#forever) (the source of the web is [here](https://github.com/merenlab/web)), and you are more than welcome to write one as well, just like the way you are welcome to not do anything at all. You've done enough already :)

Please don't forget to send me an e-mail with your shipping address and t-shirt size!


Thanks again,

**Pull request merged**
