### PR TITLE
get_values_of_gene_level_coverage_stats_as_dict("mean_coverage")

### PR DESCRIPTION
**Pull request by ShaiberAlon**
Unfortunately now I get this error that I don't understand:
```
Traceback (most recent call last):
  File "/Users/alonshaiber/github/anvio/bin/anvi-meta-pan-genome", line 60, in <module>
    pan.process()
  File "/Users/alonshaiber/github/anvio/anvio/metapanops.py", line 293, in process
    self.add_ECG_EAG_ratio_per_gene_cluster_into_pan_database()
  File "/Users/alonshaiber/github/anvio/anvio/metapanops.py", line 260, in add_ECG_EAG_ratio_per_gene_cluster_into_pan_database
    self.progress.update('Computing ratio of genes present/absent per gene cluster data ...')
  File "/Users/alonshaiber/github/anvio/anvio/terminal.py", line 125, in update
    raise TerminalError('Progress with null pid will not update for msg "%s"' % msg)
anvio.errors.TerminalError:

Terminal Error: Progress with null pid will not update for msg "Computing ratio of genes
                present/absent per gene cluster data ..."
```

But this pull request solves the previous problem.

### CODE REVIEW

**Comment by meren** [comment]
Can you see if d6fa28ad5b61ac26dc9b92cb070fc7932d2718ba fixes this?

I sent to the `summarizer-patch` branch :/

**Comment by meren** [comment]
If you pull and try again, it should work.

**Comment by ShaiberAlon** [comment]
Meren, my silly test using this file:
[internal-genomes.txt](https://github.com/merenlab/anvio/files/1644434/internal-genomes.txt)
and using these command lines (in the output directory of mini test):
```bash
anvi-gen-genomes-storage -i internal-genomes.txt -o SAMPLES-GENOMES.db
anvi-pan-genome -g SAMPLES-GENOMES.db -n s
anvi-meta-pan-genome -i internal-genomes.txt -g SAMPLES-GENOMES.db -p s/s-PAN.db
```
Still runs into the following error:
```bash
WARNING
==============================================================
ProfileSuperClass found a collection focus, which means it will be initialized
using only the splits in the profile database that are affiliated with the
collection CONCOCT and bins "Bin_1, Bin_2, Bin_3" it describes.

Auxiliary Data ..............................................: Found: /Users/alonshaiber/github/anvio/tests/sandbox/test-output-all-gene-view-branch/test-output/SAMPLES-MERGED/AUXILIARY-DATA.db (v. 2)
Profile Super ...............................................: Initialized with all 35 splits: /Users/alonshaiber/github/anvio/tests/sandbox/test-output-all-gene-view-branch/test-output/SAMPLES-MERGED/PROFILE.db (v. 23)
Taxonomy ....................................................: Initiated for taxonomic level for "t_genus"


Config Error: Something is wrong... It seems you generated a pangenome with an internal
              genomes file that is not identical to the internal genomes file you are using to
              run this program.

```

**Comment by ShaiberAlon** [comment]
Meren I have made some changes, now my test works, please take a look and if you agree, merge this branch with master, and then I will run the oral metapan again. Thank you!

**Comment by meren** [comment]
I made a little change in your commit. just for the sake of consistency.

we will have to come back to this and fix this mess in a different way later.

**Comment by meren** [comment]
please test it one more time and merge it to master :)

thank you very much for your patience, alon.

**Comment by ShaiberAlon** [comment]
My pleasure! Also, to my understanding I'm the first one to use the new `anvi-meta-pan-genome`, so when you are at the forefront you have to have patience ;-)

**Comment by meren** [comment]
Well, if I didn't screw everything up by using a test case where genome names were identical to the bin names in collections in the internal genomes file none of these would have happened and you would have used your time for better things :/

**Pull request merged**
