### PR TITLE
Doc edits

### PR DESCRIPTION
**Pull request by ekiefl**
I went through some of the programs I wrote or are familiar with and edited things along the way. The branch is erroneously called doc-proofs, but they are not proofs. They are just edits. 

I am so impressed with how our documentation framework and content is shaping up--glad that I am finally contributing to it.

Please take a quick look and make sure things are up to standards.

### CODE REVIEW

**Comment by ekiefl** [comment]
Oh, by the way. I am sorry for doing this, but currently each paragraph lies on a single line. This was horrible to work with for my IDE, so I split most of the paragraphs I edited into 100-character lines. Does this make things crappy for you one-liners?

**Comment by meren** [comment]
Yay! :) Thank you, Evan!

> Oh, by the way. I am sorry for doing this, but currently each paragraph lies on a single line. This was horrible to work with for my IDE, so I split most of the paragraphs I edited into 100-character lines. Does this make things crappy for you one-liners?

I hate to ask this but is it too difficult to turn them into single lines for the sake of consistency across all docs?

It was hell for me as well, but then I added the following to make my wrapped lines in vim workable seamlessly:

``` vim
" move through wrapped lines
nnoremap j gj
nnoremap k gk
```

**Comment by ekiefl** [comment]
Ok all should be well now. Those are some handy remaps. I also added

```
vnoremap j gj
vnoremap k gk
:set linebreak
```

**Comment by meren** [comment]
How did I not have these!

Thanks, Evan!

**Comment by ekiefl** [comment]
> How did I not have these!
> 
> Thanks, Evan!

Ok furthermore, you can have these settings _only_ for markdown by doing the following:

1. Make sure you have these in your `~/.vimrc`:

```
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
```

There is no harm keeping those in your `vimrc`, and it is indeed useful to have them in your `vimrc` if you want to manually `:set wrap` on files that are _not_ markdown files.

2. Make a file in `~/.vim/ftplugin/markdown.vim` (make any necessary parent directories):

```
:setlocal wrap
:setlocal linebreak
```

Now, whenever the filetype is markdown, lines will be wrapped and line breaks will occur at white spaces (not in the middle of words).

3. The final thing is to define how a markdown filetype should be detected. To do this, make the following file in `~/.vim/ftdetect/markdown.vim` (make any necessary parent directories):

```
au BufRead,BufNewFile *.md set filetype=markdown
```

If we create a "how to contribute" document, we could add this in a small section to help other `vim` users.

**Pull request merged**
