### PR TITLE
changed the --cogs-data-dir to reflect what is on the COG tutorial

### PR DESCRIPTION
**Pull request by fauziharoon**
Followed the tutorial on http://merenlab.org/2016/10/25/cog-annotation/ and realized there was this constant error below - `anvi-setup-ncbi-cogs: error: unrecognized arguments: --cogs-data-dir .`

Just a small fix.

### CODE REVIEW

**Comment by meren** [comment]
Thank you very much, Fauzi!

**Comment by fauziharoon** [comment]
My pleasure!

**Comment by meren** [comment]
Oh, I just realized after accepting this PR that the change should be made in the tutorial :)

The codebase likes the other way around, it seems:

```bash
$ grep 'cog-data-dir' * -nr
anvio/__init__.py:285:    'cog-data-dir': (
anvio/__init__.py:286:            ['--cog-data-dir'],
Binary file anvio/__init__.pyc matches
Binary file anvio/__pycache__/__init__.cpython-35.pyc matches
Binary file anvio/__pycache__/cogs.cpython-35.pyc matches
anvio/cogs.py:81:                                time to point the right directory using the --cog-data-dir parameter." % \
anvio/cogs.py:242:                                maybe you can use the `--cog-data-dir` parameter if it is applicable? No? None\
Binary file anvio/cogs.pyc matches
anvio/drivers/emapper.py:69:                                a specific path, you can use `--cog-data-dir` parameter to show anvi'o where it is. If you\
Binary file anvio/drivers/emapper.pyc matches
bin/anvi-run-ncbi-cogs:37:    parser.add_argument(*anvio.A('cog-data-dir'), **anvio.K('cog-data-dir'))
bin/anvi-setup-ncbi-cogs:29:    parser.add_argument('--cog-data-dir', default=None, type=str, help="The directory for COG data to be stored. If you leave it\
bin/anvi-summarize:72:    groupC.add_argument(*anvio.A('cog-data-dir'), **anvio.K('cog-data-dir'))
build/lib.macosx-10.11-x86_64-3.5/anvio/__init__.py:282:    'cog-data-dir': (
build/lib.macosx-10.11-x86_64-3.5/anvio/__init__.py:283:            ['--cog-data-dir'],
build/lib.macosx-10.11-x86_64-3.5/anvio/cogs.py:81:                                time to point the right directory using the --cog-data-dir parameter." % \
build/lib.macosx-10.11-x86_64-3.5/anvio/cogs.py:238:                                maybe you can use the `--cog-data-dir` parameter if it is applicable? No? None\
build/lib.macosx-10.11-x86_64-3.5/anvio/drivers/emapper.py:69:                                a specific path, you can use `--cog-data-dir` parameter to show anvi'o where it is. If you\
build/scripts-3.5/anvi-run-ncbi-cogs:37:    parser.add_argument(*anvio.A('cog-data-dir'), **anvio.K('cog-data-dir'))
build/scripts-3.5/anvi-script-run-eggnog-mapper:54:    parser.add_argument('--cog-data-dir', default=None, type=str, help="The directory path for your COG setup\
build/scripts-3.5/anvi-setup-ncbi-cogs:29:    parser.add_argument('--cog-data-dir', default=None, type=str, help="The directory for COG data to be stored. If you leave it\
build/scripts-3.5/anvi-summarize:72:    groupC.add_argument(*anvio.A('cog-data-dir'), **anvio.K('cog-data-dir'))
sandbox/anvi-script-run-eggnog-mapper:54:    parser.add_argument('--cog-data-dir', default=None, type=str, help="The directory path for your COG setup\
```

I made the change in the tutorial: 

https://github.com/merenlab/web/commit/ea18ce39feb01487c315bd5659097fb6b9d7755f


Best,

**Comment by fauziharoon** [comment]
Got it. thanks!

**Pull request merged**
