### PR TITLE
anvi-report-inversions

### PR DESCRIPTION
**Pull request by FlorianTrigodet**
This PR introduces a WEALTH of new features added into the anvi'o framework to study active inversions in metagenomes. While it is close to being merged to the main repository, we have the following outstanding issues to be addressed in it:

 - [x]  make `--only-report-from` more flexible to use any contig's position. Right now, I can only use the exact start and stop positions that already match the parameter to find region of interest (min cov, min length, min dist between stretches, nts to pad). 
 - [x] compute inversion activity: if any reads are found for a given pair of inv/sample, then there should alway be a row for the true oligo (match reference contig) with min 0 reads and min 0% if no reads where found. 
- [x] Create anvi'o program docs for under `anvio/docs/programs/anvi-report-inversions.md` to briefly describe the major steps, key parameters, input file formats, example runs, and the resulting output files related to the `anvi-report-inversions`.

### CODE REVIEW

**Comment by FlorianTrigodet** [comment]
Well, apparently the last commit 3aaaea713a4ba0b9b63f9837c3916c422830b8a1 worked! 
Thanks @ivagljiva for checking on it.

**Comment by meren** [comment]
Hey @FlorianTrigodet, thanks for addressing the adding an additional row for true oligos with 0 matches. I also added another item to the PR about a brief documentation of the program.

By the way, how can we make `--only-report-from` more flexible? For instance, we could say `--only-report-from` will take a contig name and only report inversions from that contig,

```
anvi-report-inversions -c CONTIGS.db
                       (...)
                       --only-report-from contig_name
                       (...)
```

 But it doesn't work for circular genomes since there is only a single contig in them. We can add two more parameters,

```
anvi-report-inversions -c CONTIGS.db
                       (...)
                       --only-report-from contig_name \
                       --only-report-start-pos INT \
                       --only-report-end-pos INT \
                       (...)
```

And this way the user could define an approximate range, and the code can focus only those inversions that start and end in between these numbers. Does it sound like a good solution to you?

**Comment by FlorianTrigodet** [comment]
Yes, it would be a very good solution indeed!

**Comment by meren** [comment]
Hey @FlorianTrigodet, this now works:

```
anvi-report-inversions -P bams-and-profiles.txt \
                                       --target-contig B_fragilis_ARW016_000000000001 \
                                       --target-region-start 4500000
                                       --target-region-end 5100000
```

But I just realized something: very distant inversions, where FWD/FWD and REV/REV reads look like this:

image

coverage stretches will be considered independently, and palindromes will be missed. Am I wrong?

**Comment by FlorianTrigodet** [comment]
That's correct. If these region are more than 2000bp away (see default of `--min-distance-between-independent-stretches`) we would miss the palindrome. 

These are rare cases of very large inversions. Nevertheless, the smaller regions with coverage (in red) will be reported in the ALL-STRETCHES-CONSIDERED.txt file. As a user, I would see that a very high coverage of REV/REV & FWD/FWD for these regions with no palindrome found. Then I can use the new `--target` option with very flexible parameter like a very large `--min-distance-between-independent-stretches`, and `--check-all-palindromes`.

**Comment by FlorianTrigodet** [comment]
I just had this error message: 
```
[25 Feb 22 15:35:52 Recovering genomic context surrounding invers (...) ETA: 0s
✖ anvi-report-inversions encountered an error after 0:29:40.712567


Config Error: Query on genes_in_contigs with the where clause of 'contig='KC_000000113190' and
              source='prodigal'' did not return anything.
```
And yes, this is a small contig (~1kbp) with no genes.

**Comment by meren** [comment]
can you please re-run the same command with a `--debug` flag?

**Comment by FlorianTrigodet** [comment]
```
[25 Feb 22 16:30:13 Recovering genomic context surrounding inv (...) ETA: ∞:∞:∞
✖ anvi-report-inversions encountered an error after 0:01:36.845365

Traceback for debugging
================================================================================
  File "/project2/meren/PEOPLE/trigodet/github/anvio/bin/anvi-report-inversions", line 159, in <module>
    main(args)
  File "/project2/meren/PEOPLE/trigodet/github/anvio/anvio/terminal.py", line 875, in wrapper
    program_method(*args, **kwargs)
  File "/project2/meren/PEOPLE/trigodet/github/anvio/bin/anvi-report-inversions", line 26, in main
    I.process()
  File "/project2/meren/PEOPLE/trigodet/github/anvio/anvio/inversions.py", line 1214, in process
    self.recover_genomic_context_surrounding_inversions()
  File "/project2/meren/PEOPLE/trigodet/github/anvio/anvio/inversions.py", line 733, in recover_genomic_context_surrounding_inversions
    gene_calls_per_contig[contig_name] = contigs_db.db.get_some_rows_from_table_as_dict(t.genes_in_contigs_table_name, where_clause=where_clause)
  File "/project2/meren/PEOPLE/trigodet/github/anvio/anvio/db.py", line 989, in get_some_rows_from_table_as_dict
    raise ConfigError("Query on %s with the where clause of '%s' did not return anything." % (table_name, where_clause))
================================================================================


Config Error: Query on genes_in_contigs with the where clause of 'contig='KC_000000113190' and
              source='prodigal'' did not return anything.
```

**Comment by meren** [comment]
Thanks. This problem should be fixed now :)

**Comment by FlorianTrigodet** [comment]
Found a bug when there is no inversion:
```
REPORTING OUTPUTS
===============================================
Inversions in S01 ............................: No true inversions in this one :/
Inversions in S02 ............................: No true inversions in this one :/
Inversions in S03 ............................: No true inversions in this one :/

Reporting file for consensus inversions ......: 08_INVERSION_TARGET/INVERSIONS-CONSENSUS.txt

Reporting file on all stretches considered ...: 08_INVERSION_TARGET/ALL-STRETCHES-CONSIDERED.txt

* Compute inversion activity function is speaking: There are no consensus
inversions to compute in-sample activity :/

PERFORMANCE NOTE
===============================================
You have 3 samples but 1 thread. Not all samples will be processed in parallel.
Just FYI. Now anvi'o will compute in-sample activity of consensus 0 inversions
across 3 samples. Brace yourself and please not that this can take a very long
time since for each sample, anvi'o will go through each short read to search for
two sequences per inversion. IF IT COMES TO A POINT WHERE you (or your job on
your HPC) can't continue running it, this process can be killed without any loss
of data from the previous steps, as your primary output files must have already
been reported. You can always skip this step and search for individual primers
listed in the consensus output file using the program `anvi-search-primers` with
the parameter `--min-remainder-length 6` and the flag `--only-report-remainders`
to explore inversion activity manually.

Process Process-2:
Traceback (most recent call last):
  File "/Users/ftrigodet/opt/miniconda3/envs/anvio-dev/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/ftrigodet/opt/miniconda3/envs/anvio-dev/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ftrigodet/github/anvio/anvio/inversions.py", line 928, in compute_inversion_activity_for_sample
    s = PrimerSearch(args, run=run, progress=progress)
  File "/Users/ftrigodet/github/anvio/anvio/sequencefeatures.py", line 68, in __init__
    raise ConfigError("This class is being initialized incorrectly :/ The `args` object must either include "
anvio.errors.ConfigError:

Config Error: This class is being initialized incorrectly :/ The `args` object must either
              include path for a `primers-txt` file through `primers_txt` parameter, or a
              dictionary for a primers dictionary through `primers_dict` parameter. See online
              help for more.
```

**Comment by meren** [comment]
> Found a bug when there is no inversion

Fixed :) Thank you!

**Comment by meren** [comment]
Is this ready to merge?

**Comment by meren** [comment]
Or should we do it once we have the R script? :)

**Comment by FlorianTrigodet** [comment]
Let's merge now! I'll make another PR for the R script.

**Pull request merged**
