### PR TITLE
removing useless code that is causing collisions in multi-user enviro…

### PR DESCRIPTION
**Pull request by jmeppley**
…nments

### CODE REVIEW

**Comment by meren** [comment]
thanks, John! :) clearly @tdelmont should be more careful with his changes in the repository. we don't have time with such irresponsible coding.

**Comment by tdelmont** [comment]
Yes, I apology. I am a bit lost with all the contributions of made in this so called "code",
so thanks for cleaning after me :)

**Comment by meren** [comment]
@tdelmont, well, I think you owe John a beer.

**Comment by tdelmont** [comment]
perfect, you get me the flight ticket, I will pay both of you a beer!

**Pull request merged**
