### PR TITLE
`anvi-run-hmms --get-domtable-output` input

### PR DESCRIPTION
**Pull request by mschecht**
Hi Iva, 

I think this flag for `anvi-run-hmms` does not require any input string. I ran `run_all_tests_.sh` and everything checks out but wanted your opinion first before committing to `main`

Thanks!

### CODE REVIEW

**Comment by meren** [comment]
While we are on this topic, can we also do something about the fact that there are two very different parameters for `anvi-run-hmms` and `anvi-script-filter-hmm-hits-table`:

https://merenlab.org/software/anvio/help/main/programs/anvi-script-filter-hmm-hits-table/

And this current flag does not even match to either mentioned in the documentation 😂 

Perhaps the flag for both could be `--domain-hits-table`, which is what it really is, and in `anvi-run-hmms` it would be used to report the table, in `anvi-script-filter-hmm-hits-table` it would be expected as an input to filter hits.

The docs and snakemake workflows will likely be updated with such a change, too.

**Comment by mschecht** [comment]
> Perhaps the flag for both could be --domain-hits-table, which is what it really is, and in anvi-run-hmms it would be used to report the table, in anvi-script-filter-hmm-hits-table it would be expected as an input to filter hits.

That's a great point @meren , I addressed this in the most recent commits. I also ran `run_all_tests.sh` and think this is ready for merging.

**Comment by ivagljiva** [comment]
Sorry for the delay @mschecht! These changes look good to me :)

**Comment by mschecht** [comment]
Thanks @ivagljiva!

**Comment by meren** [comment]
Thank you both!

**Pull request merged**
