### PR TITLE
Generating docs with GPT-4

### PR DESCRIPTION
**Pull request by ekiefl**
Hey @merenlab/all I thought this was quite interesting and thought I would share.

I've been exploring use cases for using chat-gpt and one thing I wanted to explore was how well it could generate docstrings. Spoiler alert: very accurately. This isn't a serious PR (I didn't even finish the db.py module), but I think the results are quite impressive.

I've posted the transcript of my conversation with Chat GPT-4 that has led to these docstrings.

### CODE REVIEW

**Comment by meren** [comment]
holy smokes :) what a great idea!

**Comment by meren** [comment]
How much manual curation is involved here for this commit?

**Comment by meren** [comment]
(asking because I couldn't find where you posted the transcript of your convo (am I being thick? is this literally a copy-paste from the prompt into `db.py`?))

**Comment by ekiefl** [comment]
Lol you're right. Whoops, I meant to post it in this convo. Here it is:

## Prompt:
I would like you to help me write some docstrings for a module called \`db.py\` that belongs in anvi'o. I'm sure you already know what anvi'o is. Anvi'o holds user data in dynamically managed SQLite3 databases, and \`db.py\` holds the class \`DB\`, which is the workhorse for all interfacing between anvi'o databases and python. I would like you to generate/improve the docstrings in \`DB\`. Please use Google style-guide formatting. Don't describe the type of arguments/attributes. Let's do a test drive with the following function. Please generate a docstring: \`\`\`python def \_display\_db\_calls(func): def inner(self, \*args, \*\*kwargs): if self.read\_only: raise ConfigError(f"Cannot call \`DB.{func.\_\_name\_\_}\` in read-only instance") else: return func(self, \*args, \*\*kwargs) return inner \`\`\`

## Response:
```python
def _display_db_calls(func):
    """
    A decorator to ensure that a database function can only be called when the `DB` instance is not read-only.
    
    This decorator wraps a given function and checks whether the `DB` instance is read-only before allowing the
    function to be called. If the `DB` instance is read-only, a `ConfigError` is raised with a message
    indicating that the specific function cannot be called on a read-only instance.

    Args:
        func (function): The function to be wrapped by the decorator.

    Returns:
        function: The wrapped function that checks for read-only instances before executing.

    Raises:
        ConfigError: If the `DB` instance is read-only and the wrapped function is called.
    """
    def inner(self, *args, **kwargs):
        if self.read_only:
            raise ConfigError(f"Cannot call `DB.{func.__name__}` in read-only instance")
        else:
            return func(self, *args, **kwargs)
    return inner
```

## Prompt:
Good start. That is the perfect amount of description. Moving forward, please adhere to the following amendments: 1. The header should be on the same line as the triple quotes 2. Subsequent lines of a multi-line description should be indented with 4 spaces. 3. Whatever caused you to add \` (function)\` after \`func\`, please cut that out. Ok with our procedure now described, I'm going to pass you another example: \`\`\`python def get\_list\_in\_chunks(input\_list, num\_items\_in\_each\_chunk=5000): """Yield smaller bits of a list""" for index in range(0, len(input\_list), num\_items\_in\_each\_chunk): yield input\_list\[index:index + num\_items\_in\_each\_chunk\] \`\`\`

## Response:
```python
def get_list_in_chunks(input_list, num_items_in_each_chunk=5000):
    """Yield smaller bits of a list.

    This function takes an input list and breaks it into smaller chunks, yielding each chunk one at a time.
    The size of the chunks can be controlled by the `num_items_in_each_chunk` parameter.

    Args:
        input_list (list): The input list to be divided into smaller chunks.
        num_items_in_each_chunk (int, optional): The number of items in each chunk. Defaults to 5000.

    Yields:
        list: A chunk of the input list with size `num_items_in_each_chunk`.
    """
    for index in range(0, len(input_list), num_items_in_each_chunk):
        yield input_list[index:index + num_items_in_each_chunk]
```

## Prompt:
This is good, but I noticed you're adding the type of each argument. While that is the google standard, this codebase is untyped, so I don't want you trying to infer types. Let's amend the procedure with a fourth citerion: 4. Please omit types Ok, one last try here:

## Response:
I apologize for the oversight. Here is the revised docstring without the inferred types:

```python
def get_list_in_chunks(input_list, num_items_in_each_chunk=5000):
    """Yield smaller bits of a list.

    This function takes an input list and breaks it into smaller chunks, yielding each chunk one at a time.
    The size of the chunks can be controlled by the `num_items_in_each_chunk` parameter.

    Args:
        input_list: The input list to be divided into smaller chunks.
        num_items_in_each_chunk (optional): The number of items in each chunk. Defaults to 5000.

    Yields:
        A chunk of the input list with size `num_items_in_each_chunk`.
    """
    for index in range(0, len(input_list), num_items_in_each_chunk):
        yield input_list[index:index + num_items_in_each_chunk]
```

## Prompt:
Looks great to me. To save tokens, let's add a final criterion to the procedure: 5. Refrain from writing the method body. Instead, just put \`...\`. Now, I'm going to feed you the \`DB\` class and its methods in chunks, for my own convenience. Please add/improve docstrings for thist first chunk of the class: \`\`\`python class DB: def \_\_init\_\_(self, db\_path, client\_version, new\_database=False, ignore\_version=False, read\_only=False, skip\_rowid\_prepend=False, run=terminal.Run(), progress=terminal.Progress()): self.db\_path = db\_path self.read\_only = read\_only self.version = None self.run = run self.progress = progress self.tables\_to\_exclude\_from\_db\_call\_reports = \['self', 'sqlite\_master'\] # these anonymous functions report whether the ROWID will be added # to its rows read from the database or not. if the first column of a given # table does not contain unique variables, anvi'o prepends the ROWID of each # column to index 0, unless \`skip\_rowid\_prepend\` is True self.ROWID\_PREPENDS\_ROW\_DATA = lambda table\_name: False if skip\_rowid\_prepend else tables.is\_table\_requires\_unique\_entry\_id(table\_name) self.PROPER\_SELECT\_STATEMENT = lambda table\_name: 'ROWID as "entry\_id", \*' if self.ROWID\_PREPENDS\_ROW\_DATA(table\_name) else '\*' if new\_database: filesnpaths.is\_output\_file\_writable(db\_path) else: filesnpaths.is\_file\_exists(db\_path) if new\_database and os.path.exists(self.db\_path): os.remove(self.db\_path) if self.read\_only and new\_database: raise ConfigError("One cannot create a new database that is read-only.") if not self.read\_only: self.check\_if\_db\_writable() try: self.conn = sqlite3.connect(self.db\_path) except Exception as e: raise ConfigError(f"This one time someone was not happy with '{self.db\_path}' and '{e}', they said.") self.conn.text\_factory = str self.cursor = self.conn.cursor() self.table\_names\_in\_db = self.get\_table\_names() self.db\_connected = True if new\_database: self.create\_self() self.set\_version(client\_version) else: self.version = self.get\_version() if str(self.version) != str(client\_version) and not ignore\_version: if int(self.version) > int(client\_version): progress.reset() raise ConfigError("Bad news of the day: the database at %s was generated with an anvi'o version that is 'newer' than " "the one you are actively using right now. We know, you hate to hear this, but you need to upgrade " "your anvi'o :(" % self.db\_path) else: progress.reset() raise ConfigError(f"The database at '{self.db\_path}' is outdated (this database is v{self.version} and your anvi'o installation " f"wants to work with v{client\_version}). You can migrate your database without losing any data using the " f"program \`anvi-migrate\` with either of the flags \`--migrate-safely\` or \`--migrate-quickly\`.") bad\_tables = \[table\_name for table\_name in self.table\_names\_in\_db if not tables.is\_known\_table(table\_name)\] if len(bad\_tables): raise ConfigError("You better be a programmer tinkering with anvi'o databases adding new tables or something. Otherwise we " "have quite a serious problem :/ Each table in a given anvi'o database must have an entry in the " "anvio/tables/\_\_init\_\_.py dictionary \`table\_requires\_unique\_entry\_id\` to explicitly define whether anvi'o " "should add a unique entry id for its contents upon retrieval as a dictionary. The following tables " "in this database do not satisfy that: %s." % (', '.join(\[f"'{t}'" for t in bad\_tables\]))) def \_\_enter\_\_(self): return self def \_\_exit\_\_(self, \*args): self.disconnect() def \_display\_db\_calls(func): def inner(self, \*args, \*\*kwargs): if self.read\_only: raise ConfigError(f"Cannot call \`DB.{func.\_\_name\_\_}\` in read-only instance") else: return func(self, \*args, \*\*kwargs) return inner def \_not\_if\_read\_only(func): def inner(self, \*args, \*\*kwargs): if self.read\_only: raise ConfigError(f"Cannot call \`DB.{func.\_\_name\_\_}\` in read-only instance") else: return func(self, \*args, \*\*kwargs) return inner \`\`\`

## Response:
```python
class DB:
    """Anvi'o SQLite3 database management class.

    This class provides an interface for working with anvi'o SQLite3 databases. It allows for
    creating and managing tables, running queries, and interacting with the data in the database.
    """

    def __init__(self, db_path, client_version, new_database=False, ignore_version=False, read_only=False, skip_rowid_prepend=False,
                 run=terminal.Run(), progress=terminal.Progress()):
        """Initialize the DB instance.

        Args:
            db_path: The path to the SQLite3 database file.
            client_version: The anvi'o client version associated with the database.
            new_database (optional): Whether to create a new database. Defaults to False.
            ignore_version (optional): Whether to ignore version checking. Defaults to False.
            read_only (optional): Whether the database should be opened in read-only mode. Defaults to False.
            skip_rowid_prepend (optional): Whether to skip prepending ROWID to rows in some tables. Defaults to False.
            run (optional): A terminal.Run() instance. Defaults to a new terminal.Run() instance.
            progress (optional): A terminal.Progress() instance. Defaults to a new terminal.Progress() instance.
        """
        ...

    def __enter__(self):
        """Allow the DB instance to be used in a 'with' statement."""
        ...

    def __exit__(self, *args):
        """Clean up the DB instance upon exiting a 'with' statement."""
        ...

    def _display_db_calls(func):
        """A decorator to ensure that a database function can only be called when the DB instance is not read-only.

        This decorator wraps a given function and checks whether the DB instance is read-only before allowing the
        function to be called. If the DB instance is read-only, a ConfigError is raised with a message
        indicating that the specific function cannot be called on a read-only instance.

        Args:
            func: The function to be wrapped by the decorator.

        Returns:
            The wrapped function that checks for read-only instances before executing.

        Raises:
            ConfigError: If the DB instance is read-only and the wrapped function is called.
        """
        ...

    def _not_if_read_only(func):
        """A decorator to ensure that a database function can only be called when the DB instance is not read-only.

        This decorator is an alternative to _display_db_calls with the same functionality.

        Args:
            func: The function to be wrapped by the decorator.

        Returns:
            The wrapped function that checks for read-only instances before executing.

        Raises:
            ConfigError: If the DB instance is read-only and the wrapped function is called.
        """
        ...
```

## Prompt:
That's great. Feel free to describe what the method does more verbosely if the method logic is not straight forward. Moving on: \`\`\`python def get\_version(self): try: return self.get\_meta\_value('version') except: raise ConfigError("%s does not seem to be a database generated by anvi'o :/" % self.db\_path) def check\_if\_db\_writable(self): check\_counter = 0 check\_interval = 1 # in seconds check\_limit = 300 # 5 minutes, in seconds journal\_path = self.db\_path + '-journal' while(check\_counter < check\_limit and filesnpaths.is\_file\_exists(journal\_path, dont\_raise=True)): if check\_counter == 0: # print only once self.run.info\_single("It seems the database at '%s' currently used by another process " "for writing operations. Anvi'o refuses to work with this database to avoid corrupting it. " "If you think this is a mistake, you may stop this process and delete the lock file at '%s' after making sure " "no other active process is using it for writing. In case this program is run by an automatic workflow manager like snakemake " "Anvi'o will periodically check if the journal file still exists for total of %d minutes. If the database is still not writable " "after that time, Anvi'o will stop running. " % (os.path.abspath(self.db\_path), os.path.abspath(journal\_path), int(check\_limit/60))) time.sleep(check\_interval) check\_counter += check\_interval if not check\_counter < check\_limit: raise ConfigError("Database is not writable.") @\_not\_if\_read\_only def create\_self(self): self.\_exec('''CREATE TABLE self (key text, value text)''') @\_not\_if\_read\_only def drop\_table(self, table\_name): """Delete a table in the database if it exists""" self.\_exec('''DROP TABLE IF EXISTS %s;''' % table\_name) @\_not\_if\_read\_only def create\_table(self, table\_name, fields, types): if len(fields) != len(types): raise ConfigError("create\_table: The number of fields and types has to match.") db\_fields = ', '.join(\['%s %s' % (t\[0\], t\[1\]) for t in zip(fields, types)\]) self.\_exec('''CREATE TABLE %s (%s)''' % (table\_name, db\_fields)) self.commit() self.table\_names\_in\_db = self.get\_table\_names() @\_not\_if\_read\_only def set\_version(self, version): self.set\_meta\_value('version', version) self.commit() @\_not\_if\_read\_only def set\_meta\_value(self, key, value): self.remove\_meta\_key\_value\_pair(key) self.\_exec('''INSERT INTO self VALUES(?,?)''', (key, value,)) self.commit() @\_not\_if\_read\_only def remove\_meta\_key\_value\_pair(self, key): self.\_exec('''DELETE FROM self WHERE key="%s"''' % key) self.commit() \`\`\`

## Response:
```python
    def get_version(self):
        """Get the anvi'o version associated with the database.

        Returns:
            The version of the anvi'o client that created the database.

        Raises:
            ConfigError: If the database doesn't appear to be generated by anvi'o.
        """
        ...

    def check_if_db_writable(self):
        """Check if the database is writable.

        This function checks if the database is currently locked by another process for writing operations.
        If it is locked, the function will wait for a maximum of 5 minutes (configurable) before raising
        a ConfigError. During this time, it will periodically check if the lock has been released.

        Raises:
            ConfigError: If the database is not writable after the maximum waiting time.
        """
        ...

    def create_self(self):
        """Create the 'self' table in the database.

        The 'self' table is a meta table used to store key-value pairs related to the database.
        """
        ...

    def drop_table(self, table_name):
        """Delete a table in the database if it exists.

        Args:
            table_name: The name of the table to be dropped.
        """
        ...

    def create_table(self, table_name, fields, types):
        """Create a new table in the database with the specified fields and types.

        Args:
            table_name: The name of the new table to be created.
            fields: A list of field names for the new table.
            types: A list of data types corresponding to the field names.

        Raises:
            ConfigError: If the number of fields and types do not match.
        """
        ...

    def set_version(self, version):
        """Set the anvi'o version associated with the database.

        Args:
            version: The version of the anvi'o client to be associated with the database.
        """
        ...

    def set_meta_value(self, key, value):
        """Set a meta key-value pair in the 'self' table.

        If the key already exists in the table, the existing key-value pair will be removed
        before the new one is added.

        Args:
            key: The meta key to be set.
            value: The meta value associated with the key.
        """
        ...

    def remove_meta_key_value_pair(self, key):
        """Remove a meta key-value pair from the 'self' table.

        Args:
            key: The meta key to be removed.
        """
        ...
```

## Prompt:
\`\`\`python @\_not\_if\_read\_only def update\_meta\_value(self, key, value): self.remove\_meta\_key\_value\_pair(key) self.set\_meta\_value(key, value) @\_not\_if\_read\_only def copy\_paste(self, table\_name, source\_db\_path, append=False): """Copy \`table\_name\` data from another database (\`source\_db\_path\`) into yourself Arguments ========= append : bool, False If True, the table is appened to the source DB, rather than replaced. """ source\_db = DB(source\_db\_path, None, ignore\_version=True) num\_entries\_in\_source = source\_db.get\_row\_counts\_from\_table(table\_name) if not num\_entries\_in\_source: return # we are done with the source DB python object. The rest we do in SQL # for huge performance gains source\_db.disconnect() if not append: self.\_exec('''DELETE FROM %s''' % table\_name) self.\_exec('''ATTACH "%s" AS source\_db''' % source\_db\_path) self.\_exec('''INSERT INTO main.%s SELECT \* FROM source\_db.%s''' % (table\_name, table\_name)) self.\_exec('''DETACH DATABASE "source\_db"''') def \_fetchall(self, response, table\_name): """Wrapper for fetchall""" DISPLAY\_DB\_CALLS = False if table\_name in self.tables\_to\_exclude\_from\_db\_call\_reports else anvio.DISPLAY\_DB\_CALLS if DISPLAY\_DB\_CALLS: sql\_exec\_timer = terminal.Timer() results = response.fetchall() if DISPLAY\_DB\_CALLS: self.run.info("fetchall", f"{sql\_exec\_timer.time\_elapsed()}", mc='yellow', nl\_after=1) return results def get\_max\_value\_in\_column(self, table\_name, column\_name, value\_if\_empty=None, return\_min\_instead=False): """Get the maximum OR minimum column value in a table Parameters ========== value\_if\_empty : object, None If not None and table has no entries, value returned is value\_if\_empty. """ response = self.\_exec("""SELECT %s(%s) FROM %s""" % ('MIN' if return\_min\_instead else 'MAX', column\_name, table\_name)) rows = self.\_fetchall(response, table\_name) val = rows\[0\]\[0\] if isinstance(val, type(None)): return value\_if\_empty try: val = int(val) except ValueError: pass return val \`\`\`

## Response:
```python
    def update_meta_value(self, key, value):
        """Update a meta key-value pair in the 'self' table.

        This function first removes the existing key-value pair (if any) and then sets the new
        key-value pair.

        Args:
            key: The meta key to be updated.
            value: The new meta value associated with the key.
        """
        ...

    def copy_paste(self, table_name, source_db_path, append=False):
        """Copy data from a table in another database into the current database.

        Args:
            table_name: The name of the table to copy data from.
            source_db_path: The path of the source database.
            append: If True, the table is appended to the source DB, rather than replaced. (default: False)
        """
        ...

    def _fetchall(self, response, table_name):
        """Wrapper for fetchall method on a response object from a database query.

        Args:
            response: A response object from a database query.
            table_name: The name of the table being queried.

        Returns:
            A list of tuples with the fetched data.
        """
        ...

    def get_max_value_in_column(self, table_name, column_name, value_if_empty=None, return_min_instead=False):
        """Get the maximum or minimum value in a specified column of a table.

        Args:
            table_name: The name of the table to query.
            column_name: The name of the column to find the maximum or minimum value.
            value_if_empty: If not None and table has no entries, the value returned is value_if_empty. (default: None)
            return_min_instead: If True, returns the minimum value instead of the maximum value. (default: False)

        Returns:
            The maximum or minimum value in the specified column, or value_if_empty if the table is empty.
        """
        ...
```

## Prompt:
\`\`\`python def get\_meta\_value(self, key, try\_as\_type\_int=True, return\_none\_if\_not\_in\_table=False): """if try\_as\_type\_int, value is attempted to be converted to integer. If it fails, no harm no foul.""" response = self.\_exec("""SELECT value FROM self WHERE key='%s'""" % key) rows = self.\_fetchall(response, 'self') if not rows and return\_none\_if\_not\_in\_table: return None if not rows: raise ConfigError("A value for '%s' does not seem to be set in table 'self'." % key) val = rows\[0\]\[0\] if isinstance(val, type(None)): return None if try\_as\_type\_int: try: val = int(val) except ValueError: pass return val def commit(self): self.conn.commit() def disconnect(self): if self.db\_connected: self.conn.commit() self.conn.close() self.db\_connected = False else: # it is already disconnected pass def \_exec(self, sql\_query, value=None): """Execute an arbitrary sql statement Notes ===== - This is a private method, and so it is presumed whoever uses it knows what they are doing. For this reason, it is not decorated with \_not\_if\_read\_only. It is therefore possible to write to the DB using this method, even with self.read\_only = True """ # this is an ugly workaround to not display DB calls if they involve talbes # such as \`self\` or \`sqlite\_master\` (comlete list in self.tables\_to\_exclude\_from\_db\_call\_reports). # Otherwise when the user sets the \`--display-db-calls\` flag, the output is heavily # dominated by queries to \`self\`. Even though Meren is implementing this sadness, # Iva agreed to it as well. Just saying: if any(table\_name for table\_name in self.tables\_to\_exclude\_from\_db\_call\_reports if f' {table\_name} ' in sql\_query): DISPLAY\_DB\_CALLS = False else: DISPLAY\_DB\_CALLS = anvio.DISPLAY\_DB\_CALLS if DISPLAY\_DB\_CALLS: self.progress.reset() self.run.warning(None, header='EXECUTING SQL', lc='yellow', nl\_before=1) self.run.info\_single(f"{os.path.abspath(self.db\_path)}", cut\_after=None, level=0, mc='yellow', nl\_after=1) self.run.info\_single(f"{sql\_query}", cut\_after=None, level=0, mc='yellow', nl\_after=1) sql\_exec\_timer = terminal.Timer() if value: ret\_val = self.cursor.execute(sql\_query, value) else: ret\_val = self.cursor.execute(sql\_query) if DISPLAY\_DB\_CALLS: self.run.info("exec", f"{sql\_exec\_timer.time\_elapsed()}", mc='yellow') self.commit() return ret\_val def \_exec\_many(self, sql\_query, values): """Execute many sql statements Notes ===== - This is a private method, and so it is presumed whoever uses it knows what they are doing. For this reason, it is not decorated with \_not\_if\_read\_only. It is therefore possible to write to the DB using this method, even with self.read\_only = True """ chunk\_counter = 0 for chunk in get\_list\_in\_chunks(values): if anvio.DISPLAY\_DB\_CALLS: header = f"MULTI SQL // {chunk\_counter} of {len(values)} with {len(chunk)} {len(chunk)} entries" self.run.warning(None, header=header, progress=self.progress, lc='yellow') self.run.info\_single(f"{sql\_query}", nl\_after=1, cut\_after=None, level=0, mc='yellow') sql\_exec\_timer = terminal.Timer() self.cursor.executemany(sql\_query, chunk) if anvio.DISPLAY\_DB\_CALLS: self.run.info("exec", f"{sql\_exec\_timer.time\_elapsed()}", mc='yellow') chunk\_counter += 1 return True \`\`\`

## Response:
```python
    def get_meta_value(self, key, try_as_type_int=True, return_none_if_not_in_table=False):
        """Get the value associated with a key from the 'self' table.

        Args:
            key: The meta key to search for.
            try_as_type_int: If True, attempts to convert the value to an integer. If it fails, returns the original value. (default: True)
            return_none_if_not_in_table: If True, returns None if the key is not found in the table. (default: False)

        Returns:
            The value associated with the key, or None if the key is not found and return_none_if_not_in_table is True.
        """
        ...

    def commit(self):
        """Commit any pending transactions to the database."""
        ...

    def disconnect(self):
        """Disconnect from the database, committing any pending transactions and closing the connection."""
        ...

    def _exec(self, sql_query, value=None):
        """Execute an arbitrary SQL statement.

        Note: This is a private method and it is assumed that whoever uses it knows what they are doing.
        It is not decorated with _not_if_read_only, so it is possible to write to the DB using this method,
        even with self.read_only = True.

        Args:
            sql_query: The SQL query to execute.
            value: A single parameter to use in the SQL query (optional).

        Returns:
            The result of the executed SQL query.
        """
        ...

    def _exec_many(self, sql_query, values):
        """Execute many SQL statements.

        Note: This is a private method and it is assumed that whoever uses it knows what they are doing.
        It is not decorated with _not_if_read_only, so it is possible to write to the DB using this method,
        even with self.read_only = True.

        Args:
            sql_query: The SQL query to execute.
            values: A list of values to be used as parameters in the SQL query.

        Returns:
            True if all SQL statements were executed successfully.
        """
        ...
```

## Prompt:
\`\`\`python @\_not\_if\_read\_only def insert(self, table\_name, values=()): query = '''INSERT INTO %s VALUES (%s)''' % (table\_name, ','.join(\['?'\] \* len(values))) return self.\_exec(query, values) @\_not\_if\_read\_only def insert\_many(self, table\_name, entries=None): if len(entries): query = '''INSERT INTO %s VALUES (%s)''' % (table\_name, ','.join(\['?'\] \* len(entries\[0\]))) return self.\_exec\_many(query, entries) @\_not\_if\_read\_only def insert\_rows\_from\_dataframe(self, table\_name, dataframe, raise\_if\_no\_columns=True): """Insert rows from a dataframe Parameters ========== raise\_if\_no\_columns : bool, True If True, if dataframe has no columns (e.g. dataframe = pd.DataFrame({})), this function returns without raising error. Notes ===== - This should one day be replaced with the following code: if 'entry\_id' in structure: # This table has an entry\_id of, we have to be aware of it if 'entry\_id' in df.columns: # The user already has an 'entry\_id' column. We assume they know what they are doing next\_available\_id = df\['entry\_id'\].max() + 1 else: num\_entries = df.shape\[0\] next\_available\_id = self.get\_max\_value\_in\_column(name, 'entry\_id', value\_if\_empty=-1) + 1 df\['entry\_id'\] = range(next\_available\_id, next\_available\_id + num\_entries) next\_available\_id += num\_entries else: next\_available\_id = None # subset columns and reorder according to the table structure df = df\[structure\] dtypes = dict(zip(structure, types)) df.to\_sql( name, self.conn, if\_exists='append', chunksize=chunksize, dtype=dtypes, index=False ) return next\_available\_id """ self.is\_table\_exists(table\_name) if not list(dataframe.columns) and not raise\_if\_no\_columns: # if the dataframe has no colums, we just return return if len(set(dataframe.columns)) != len(list(dataframe.columns)): raise ConfigError("insert\_rows\_from\_dataframe :: There is at least one duplicate column " "name in the dataframe. Here is the list of columns: \[{}\].".\\ format(", ".join(list(dataframe.columns)))) if set(dataframe.columns) != set(self.get\_table\_structure(table\_name)): raise ConfigError("insert\_rows\_from\_dataframe :: The columns in the dataframe " "do not equal the columns of the requested table. " "The columns from each are respectively ({}); and ({}).".\\ format(", ".join(list(dataframe.columns)), ", ".join(self.get\_table\_structure(table\_name)))) # conform to the column order of the table structure dataframe = dataframe\[self.get\_table\_structure(table\_name)\] entries = \[tuple(row) for row in dataframe.values\] self.insert\_many(table\_name, entries=entries) def is\_table\_exists(self, table\_name): if table\_name not in self.table\_names\_in\_db: raise ConfigError(f"The database at {self.db\_path} does not seem to have a table named \`{table\_name}\` :/ " f"Here is a list of table names this database knows: {', '.join(self.table\_names\_in\_db)}") \`\`\`

## Response:
```python
    @_not_if_read_only
    def insert(self, table_name, values=()):
        """Insert a new row into the specified table.

        Args:
            table_name: The name of the table to insert the row into.
            values: A tuple of values to insert as a new row.

        Returns:
            The result of the executed SQL query.
        """
        ...

    @_not_if_read_only
    def insert_many(self, table_name, entries=None):
        """Insert multiple rows into the specified table.

        Args:
            table_name: The name of the table to insert the rows into.
            entries: A list of tuples, where each tuple contains the values for a row.

        Returns:
            The result of the executed SQL query.
        """
        ...

    @_not_if_read_only
    def insert_rows_from_dataframe(self, table_name, dataframe, raise_if_no_columns=True):
        """Insert rows from a dataframe into the specified table.

        Args:
            table_name: The name of the table to insert the rows into.
            dataframe: A pandas DataFrame containing the rows to insert.
            raise_if_no_columns: If True, raises an error if the dataframe has no columns. (default: True)

        Raises:
            ConfigError: If the columns in the dataframe do not match the columns in the table.
        """
        ...

    def is_table_exists(self, table_name):
        """Check if a table with the given name exists in the database.

        Args:
            table_name: The name of the table to check for existence.

        Raises:
            ConfigError: If the table does not exist in the database.
        """
        ...
```

## Prompt:
There is an important note in the original \`insert\_rows\_from\_dataframe\`. Could you please include that? Don't rewrite the whole chunk, just that method docstring.

## Response:
```python
    @_not_if_read_only
    def insert_rows_from_dataframe(self, table_name, dataframe, raise_if_no_columns=True):
        """Insert rows from a dataframe into the specified table.

        Args:
            table_name: The name of the table to insert the rows into.
            dataframe: A pandas DataFrame containing the rows to insert.
            raise_if_no_columns: If True, raises an error if the dataframe has no columns. (default: True)

        Raises:
            ConfigError: If the columns in the dataframe do not match the columns in the table.

        Notes:
        =====
        - This should one day be replaced with the following code:
            if 'entry_id' in structure:
                # This table has an entry_id of, we have to be aware of it
                if 'entry_id' in df.columns:
                    # The user already has an 'entry_id' column. We assume they know what they are doing
                    next_available_id = df['entry_id'].max() + 1
                else:
                    num_entries = df.shape[0]
                    next_available_id = self.get_max_value_in_column(name, 'entry_id', value_if_empty=-1) + 1
                    df['entry_id'] = range(next_available_id, next_available_id + num_entries)
                    next_available_id += num_entries
            else:
                next_available_id = None

            # subset columns and reorder according to the table structure
            df = df[structure]

            dtypes = dict(zip(structure, types))

            df.to_sql(
                name,
                self.conn,
                if_exists='append',
                chunksize=chunksize,
                dtype=dtypes,
                index=False
            )

            return next_available_id
        """
        ...
```

**Comment by meren** [comment]
image

**Comment by ekiefl** [comment]
It's annoying that the user prompt isn't formatted, but hopefully you get the idea. I'm just copy pasting the class 5-6 methods at a time.

To answer your question, I didn't manually curate anything. What you see is what you get. It seems about as accurate or more accurate than the average docstring, which all too often are stale.

**Comment by meren** [comment]
It is *absolutely* very useful. Thank you very much for sending your prompt

**Review by bernhardkaindl — APPROVED** [review]

**Review by bernhardkaindl — APPROVED** [review]
@meren Do you need to review it more closely? From my experience, the GPTs/Copilot have been spot on in generating docstrings.

**Comment by meren** [comment]
Hey @bernhardkaindl, thank you very much for the ping. This clearly had fallen through the cracks :( I am merging it now!

**Comment by meren** [comment]
I think it would be great to expand this effort to the rest of the code, but I think it will take much much more supervision than the `db.py`.

In an ideal world I would like to see that effort combined with an effort to create a more sensible directory structure in the anvio directory, re-partition classes and functions into more meaningful groups. The codebase has been growing every direction without much attention to its structure :/

**Comment by ekiefl** [comment]
I agree @meren.

I feel like over time, anvio has lost its dependency flow. I imagine the codebase should exist like layers of an onion. In the very center of the onion lie the core modules. They depend only on Python primitives and the standard library. They make no reference to outer layers. A good example of this is `fastalib`. It knows about io, sys, gzip, and hashlib. But unfortunately, it also knows about `anvio` because it needs `__version__`, which bad news because `anvio.__init__` is supposed to be **the** outermost layer of the onion. Ideally, there would be a `_version` module that holds the version, and `anvio.__init__` and `fastalib` both reference that.

But besides that small technicality (which is admittedly really important to avoid circular imports), `fastalib` has remained pure. But as another example, `utils` hasn't been so lucky, in large part due to my misuse of it 😄. `utils` are designed to house primitive functionality in a package/subpackage that the modules in that package/subpackage import and use. For example, saving a nested dictionary as a TSV. But if we look at utils, the dependency flow reverses. Like, for some reason `utils` imports from `db`! If anything at all, `db` should import from `utils`.

I think the most canonical solution to this is to add some more depth to the anvio structure--currently it's very flat. For example, `anvio.utils` imports `anvio.db` because there are tons of `db` utility in `utils.py`. Ok, well that's bad, and a solution would be to make a subpackage `db/`:

```
db/
├── contigs
├── core.py
├── profile
├── structure
└── utils.py
```

This `utils.py` is now part of the db subpackage, and can house all the DB utility stuff without violating dependency flow.

In general, I think the process of adding structure could be guided by scrutinizing over each and every import and asking oneself questions like, "is module A a dependency of module B, or is it the other way around?". If you can't figure that out, you need to restructure your code.

And this won't always be easy because the classes in anvio are monolithic with tons of methods. These methods often force the class's module to import outer dependency layers when those methods should really just be functions in some currently nonexistent subpackage.

The code is 10 years old and the technical debt has piled up pretty high. It goes without saying that it's not anyone's fault--all code is garbage as they say. Small incremental improvements to the design are undoubtedly worth it, given how many people rely on anvi'o and how useful it is, but I have to admit the only satisfying solution I see is to rebuild from scratch.

**Comment by meren** [comment]
> but I have to admit the only satisfying solution I see is to rebuild from scratch

Yes, we are on the same page here 😂

**Pull request merged**
