### PR TITLE
gene popover functionality

### PR DESCRIPTION
**Pull request by metehaansever**
Since the length value was not returned from the meta.json file, I left it as static. I guess there is no Annotations value either. In addition, for missing values in some genes, for example, id: 28, we can return the values to none.

image

### CODE REVIEW

**Comment by FlorianTrigodet** [comment]
I'll add length in the json. 
I'm also working on adding DNA and AA sequences into the json. But that requires me learning more about anvi'o class etc.

**Comment by metehaansever** [comment]
> I'll add length in the json. I'm also working on adding DNA and AA sequences into the json. But that requires me learning more about anvi'o class etc.

In that case, we can merge this branch after we finish the DNA and AA functionality.

**Comment by meren** [comment]
How come there is no annotation but there is an accession for the annotation? :)

**Comment by FlorianTrigodet** [comment]
Now they do! Annotations are called 'function' in the json

**Comment by meren** [comment]
@metehaansever, please make sure the popovers has a fixed width of 900px. The contents of the annotation column should wrap in each `td`.

**Comment by FlorianTrigodet** [comment]
DNA and AA sequence are available for each gene. 
They are accessible as `DNA_sequence` and `AA_sequence` in the gene part of the json.
Now we can make a button to display these sequences :D

**Comment by FlorianTrigodet** [comment]
Oh, should I provide a fasta header like in inspect page?

**Comment by metehaansever** [comment]
> Oh, should I provide a fasta header like in inspect page?

I guess, this is a good idea because they'll copy and paste somewhere else. But I guess I can handle that on the UI :)

**Comment by FlorianTrigodet** [comment]
Now there is a fasta header in the summary (called 'header' because I have a lot of imagination this morning). 
I also fix the DNA reporting part because if the gene is in rev direction, the sequence should be reverse complemented. 
Ready for the DNA and AA button :D

**Comment by metehaansever** [comment]
we replaced the popover top to the bottom. The reason was the Function's width. And I added AA/DNA buttons.
image

**Comment by meren** [comment]
Some attention to detail please: can anyone answer why the borders for the inner div are not equally distant to the borders of the popover at all edges? No. No one can answer that. But they can make sure it is not the case :)

image

**Comment by metehaansever** [comment]
I hope, it's not the case anymore :+1: 
image

**Comment by FlorianTrigodet** [comment]
Shame on WHOEVER could have forgotten a print statement in the code ...

Looks nice to me with the latest changes. Ready for merge do you think?

**Comment by meren** [comment]
Yes! Thank you both :) Merge whenever, boss.

**Comment by meren** [comment]
(but please don't forget to update the documentation with some screenshots or whatever, so it is clear what we're generating)

**Pull request merged**
