### PR TITLE
Ability to scan tRNAs in anvi'o contigs databases

### PR DESCRIPTION
**Pull request by meren**
This PR introduces a new feature to anvi'o through a new program, `anvi-scan-trnas`, to identify transfer RNAs in contigs databases, and add them into the database as new gene calls.

An example. `Bfragilis_0100-contigs.db` is a regular contigs database on which `anvi-run-hmms` was already run:

```
anvi-get-sequences-for-hmm-hits -c Bfragilis_0100-contigs.db --list-hmm-sources
* CPSHMM [type: CPS] [num genes: 1]
* Bacteria_71 [type: singlecopy] [num genes: 71]
* Archaea_76 [type: singlecopy] [num genes: 76]
* Protista_83 [type: singlecopy] [num genes: 83]
* Ribosomal_RNAs [type: Ribosomal_RNAs] [num genes: 12]
```

When I run `anvi-scan-trnas`, this is what happens:

```
$ anvi-scan-trnas -c Bfragilis_0100-contigs.db --num-threads 5
tRNAscan-SE version found ....................: 2.0.5

Temporary dir ................................: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmpdwvvuafl
FASTA file for contigs .......................: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmpdwvvuafl/contig_sequences.fa
tRNA hits output .............................: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmpdwvvuafl/hits_file.txt
Log file .....................................: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmpdwvvuafl/log.txt
Cutoff score .................................: 20
tRNAscan-SE version found ....................: 2.0.5


CITATION
===============================================
Anvi'o will use 'tRNAScan-SE' by Chan and Lowe (doi:10.1007/978-1-4939-9173-0_1)
to identify tRNA sequences in your data. When you publish your findings, please
do not forget to properly credit their work.

Num tRNA genes parsed ........................: 77
Num tRNA genes recovered .....................: 76

WEIRD CODONS ALERT
===============================================
While anvi'o was trying to parse the output from tRNAScan-SE, it became clear
that some of the codons the tool identified was not known to anvi'o, so we
conservatively discareded those entries. Here is the list of codons that were
discareded and their frequency among your contigs: 'NNN (1)'.

Gene calls added to db .......................: 76 (from source "Transfer_RNAs")
* Temp directory is now cleaned (if you would like to keep it the next time use
the flag `--debug`).

✓ anvi-scan-trnas took 0:00:05.348886
```

Aaand voilà (notice `Transfer_RNAs` at the end):

```
 anvi-get-sequences-for-hmm-hits -c Bfragilis_0100-contigs.db --list-hmm-sources
* CPSHMM [type: CPS] [num genes: 1]
* Bacteria_71 [type: singlecopy] [num genes: 71]
* Archaea_76 [type: singlecopy] [num genes: 76]
* Protista_83 [type: singlecopy] [num genes: 83]
* Ribosomal_RNAs [type: Ribosomal_RNAs] [num genes: 12]
* Transfer_RNAs [type: Transfer_RNAs] [num genes: 61]
```

Because it goes into the HMMs tables as the `anvio/tables/trnahits.py` doctors the to fit into the HMMs workflow, everything else works. Such as,

```
$ anvi-get-sequences-for-hmm-hits -c Bfragilis_0100-contigs.db \
                                  --hmm-source Transfer_RNAs \
                                  -o trnas.fa

Contigs DB ...................................: Initialized: Bfragilis_0100-contigs.db (v. 14)
Hits .........................................: 76 hits for 1 source(s)
Mode .........................................: DNA sequences
Genes are concatenated .......................: False
Output .......................................: trnas.fa
```

The resulting file looks like this:

```
$ head -n 20 trnas.fa
>Thr_ACG___Transfer_RNAs___251692f466b8467c13e7a42bb49810d73bef551dfe212bfa1ffdbd28 bin_id:Bfragilis_0100-contigs|source:Transfer_RNAs|e_value:67.6|contig:Bfragilis_0100_000000000001|gene_callers_id:4426|start:135361|stop:135433|length:72
CCGCTATAGCTCAGTTGGTAGAGCAACGCATTCGTAACGCGTAGGTCTCCAGTTCAAGTCTGGATAGCGGCT
>Thr_ACA___Transfer_RNAs___ef00abaac23964a5cba778f8a312ad283053fb1480d3fffc6ebeb617 bin_id:Bfragilis_0100-contigs|source:Transfer_RNAs|e_value:69.6|contig:Bfragilis_0100_000000000001|gene_callers_id:4427|start:448045|stop:448120|length:75
CCTCTTTAGCTCAGTTGGCCAGAGCACGTGATTTGTAATCTCGGGGTCGTTGGTTCGAATCCGACAAGAGGCTCA
>Cys_TGC___Transfer_RNAs___f0011e5cca43be77138d81e41ad7581d31508300d703e6a8d748b93e bin_id:Bfragilis_0100-contigs|source:Transfer_RNAs|e_value:56|contig:Bfragilis_0100_000000000001|gene_callers_id:4440|start:476759|stop:476830|length:71
GGTTCCTTGGATGAGTGGTTTAGTCAGCGGTCTGCAAAACCGTGTACGGCGGTTCGAATCCGCCAGGAACC
>Ser_TCA___Transfer_RNAs___a6b63471ad154fcc5dab88bf324aed80fd4027d86e8931a32497aafd bin_id:Bfragilis_0100-contigs|source:Transfer_RNAs|e_value:65.7|contig:Bfragilis_0100_000000000001|gene_callers_id:4439|start:511856|stop:511940|length:84
GGAGAGGTGGCAGAGTGGTCGATTGCGGCGGTCTTGAAAACCGTTGTACTGCGAGGTACCCGGGGTTCGAATCCCTGTCTCTCC
>Ser_TCA___Transfer_RNAs___ae886868ba161d8e6cf92ec9367de1e7b96f988f107e63acf021cc2a bin_id:Bfragilis_0100-contigs|source:Transfer_RNAs|e_value:65.7|contig:Bfragilis_0100_000000000001|gene_callers_id:4438|start:615303|stop:615387|length:84
GGAGAGGTGGCAGAGTGGTCGATTGCGGCGGTCTTGAAAACCGTTGTACTGCGAGGTACCCGGGGTTCGAATCCCTGTCTCTCC
>Tyr_TAC___Transfer_RNAs___63295383180d2ae19cba0d2dd353dd872a9ba8ab5720ebf9cdd49e14 bin_id:Bfragilis_0100-contigs|source:Transfer_RNAs|e_value:64.3|contig:Bfragilis_0100_000000000001|gene_callers_id:4428|start:915005|stop:915087|length:82
GGCAAATACCAGAGTGGCCAAATGGGGCAGACTGTAAATCTGCTGTCTTTCGACTTCGGTGGTTCGAATCCATCTTTGCCCA
>Gly_GGA___Transfer_RNAs___3187f17f7b5d5ddd95c8b7a966e8180a9c3e89f7b4ca30dd63281d53 bin_id:Bfragilis_0100-contigs|source:Transfer_RNAs|e_value:67|contig:Bfragilis_0100_000000000001|gene_callers_id:4429|start:915096|stop:915168|length:72
CGGAAGTAGCTCAGTTGATAGAGCATTAGCCTTCCAAGCTGAGGGTCGCGGGTTTGAGCCCCGTCTTCCGCT
>Gln_CAA___Transfer_RNAs___42ecaf4d6c9ac5d80b98cce8a83358d9505b93c122ea74539c827c98 bin_id:Bfragilis_0100-contigs|source:Transfer_RNAs|e_value:48.5|contig:Bfragilis_0100_000000000001|gene_callers_id:4437|start:950062|stop:950132|length:70
TGTCCTATGGTGTAATGGTAGCACAACAGTTTTTGGTTCTGTTTGTCTAAGTTCGAATCTTGGTAGGACA
>Ile_ATC___Transfer_RNAs___1f5ae90b82f73bf28c7300336d6cea28ef4c63dd0b6df50c85547638 bin_id:Bfragilis_0100-contigs|source:Transfer_RNAs|e_value:71.6|contig:Bfragilis_0100_000000000001|gene_callers_id:4430|start:1110543|stop:1110619|length:76
GTCCTATAGCTCAGTTGGTTAGAGCGCTACACTGATAATGTAGAGGTCGGCAGTTCAACTCTGCCTGGGACTACCA
>Ala_GCA___Transfer_RNAs___329787e5a4afa1b1a3abc9bd4e11dbdd24edb38daea58b4e8facd5fc bin_id:Bfragilis_0100-contigs|source:Transfer_RNAs|e_value:71|contig:Bfragilis_0100_000000000001|gene_callers_id:4431|start:1110646|stop:1110722|length:76
GGGGATTAGCTCAGCTGGCTAGAGCATCTGCCTTGCACGCAGAGGGTCAACGGTTCGAATCCGTTATTCTCCACCA
```

So far so good.

In fact, we can even see them in the interface automatically:

image

And in the inspect page:

image

The only problem I see is that we don't actually see what amino acid and codon a given tRNA gene is about. We will have to fix that at some point:

image

_Update:_

Now it is fixed.

image

By populating gene functions table with this information enables us to search through the interface for tRNAs by amino acid they decode,

image

Highlight results in the display with one button:

image

and/or doing this without a line of additional code from the terminal:

```
anvi-search-functions -c Bfragilis_0100-contigs.db \
                                       --search-terms Trp \
                                       --verbose \
                                       --full-report full-report.txt \
                                       --include-sequences

Searching in Contigs Database ................: Bfragilis_0100-contigs.db
Contigs DB ...................................: Initialized: Bfragilis_0100-contigs.db (v. 14)
Search terms .................................: 1 found
Matches ......................................: 2 unique gene calls contained the search term "Trp"

Matching names for 'Trp' (up to 25)
===============================================
tRNA gene for amino acid Trp (codon: CAG; anticodon:CCA; score:72.9)

Items additional data compatible output ......: search_results.txt
Full report ..................................: full-report.txt


cat full-report.txt
gene_callers_id	source	accession	function	search_term	contigs	direction	rev_compd	dna_sequence	aa_sequence
4828	Transfer_RNAs	Gln_CAG_4828	tRNA gene for amino acid Trp (codon: CAG; anticodon:CCA; score:72.9)	Trp	Bfragilis_0100_000000000002_split_00063	f	False	CGGGAGTAGCTCAGTTGGTAGAGCACCGGTCTCCAAAACCGGGTGTCGGGAGTTCGAGCCTCTCCTCCCGTG
4843	Transfer_RNAs	Gln_CAG_4843	tRNA gene for amino acid Trp (codon: CAG; anticodon:CCA; score:72.9)	Trp	Bfragilis_0100_000000000002_split_00011	r	True	ACGGGAGTAGCTCAGTTGGTAGAGCACCGGTCTCCAAAACCGGGTGTCGGGAGTTCGAGCCTCTCCTCCCGT
```

I think the design is not too dirty, and being able to add tRNAs into our current HMMs infrastructure with minimal change in the codebase attests to that :) @semiller10, I think it would be great if you were to run this on a genome and make sure that things check out.

### CODE REVIEW

**Comment by xvazquezc** [comment]
How do you filter for "weird codons" and what do you mean by "weird"? Anything aside the 20 basic tRNAs? SelCys? Suppressor tRNAs? Undetermined isotypes?
I'm partial to keep all the annotations, or at least having the option to do so.

**Comment by meren** [comment]
> what do you mean by "weird"?

If what tRNAScan-SE reports is not recognized by anvi'o based on our descriptions in `anvio/constants.py` ([from here on](https://github.com/merenlab/anvio/blob/master/anvio/constants.py#L101)), then we pass them. I.e., if the codon is NNN or amino acid is called something out of the basic 20 :)

**Comment by xvazquezc** [comment]
Is there any reason for this other than simplifying the output?

Not sure if it's relevant for what you may want to do but the filtering will remove all initiator tRNAs as tRNAscan-SE refers to them as iMet.

**Comment by meren** [comment]
Great point, @xvazquezc. Do you have any example genomes in which tRNAscan-SE will find initiator tRNAs? I can test it and make sure it is covered.

I like the idea of starting conservative and expanding the inclusion criteria rather than adding everything to the database without any attention to incoming data or design compatibility and having to check if things make sense in every client program.

**Comment by meren** [comment]
The last commit in the PR populates gene functions tables with tRNAs, enabling new search opportunities. I think I'm done with this for now.

**Comment by semiller10** [comment]
I tested with the TM7x genome in honor of @ShaiberAlon, PhD pending. 43 tRNA genes have been annotated in this genome.

The first error I noticed is that `anvi-scan-trnas` reported that 43 tRNA genes were parsed and 43 were recovered, but `anvi-get-sequences-for-hmm-hits -c TM7x.db --list-hmm-sources` reported the existence of **61** tRNA genes.

Likewise, in your own test, `anvi-scan-trnas` reported that 77 tRNA genes were parsed and 76 were recovered, but `anvi-get-sequences-for-hmm-hits -c TM7x.db --list-hmm-sources` reported the existence of **61** tRNA genes, the same number as for TM7.

`anvi-get-sequences-for-hmm-hits -c TM7x.db --hmm-source Transfer_RNAs -o trnas.fa` does produce a file with 43 genes.

Strange observation: When I run `anvi-scan-trnas` with 1 or 2 threads, I do not get a statement at the end of how long `anvi-scan-trnas` took to run, but when I run with 3 or more threads, it does report that information.

Here is the genome with 1 kbp splits.

Screen Shot 2020-01-22 at 2 43 49 PM

The tRNA genes are scatted across the genome, and some lie in the ribosomal intergenic spacer region, as is common.

I didn't notice anything strange in the inspect view either.

**Comment by xvazquezc** [comment]
@meren 31 out of the 37 novel archaeal genomes I got [here](https://zenodo.org/record/3365725#.XijND-HZWuU) (those with code name `LFW_*`) have iMet-tRNA. Most also have tRNAs with introns, in case you need to check it out. I'll send you an email with a single genome so you don't need to download the whole thing

**Comment by meren** [comment]
> The first error I noticed is that anvi-scan-trnas reported that 43 tRNA genes were parsed and 43 were recovered, but anvi-get-sequences-for-hmm-hits -c TM7x.db --list-hmm-sources reported the existence of 61 tRNA genes.
> 
> Likewise, in your own test, anvi-scan-trnas reported that 77 tRNA genes were parsed and 76 were recovered, but anvi-get-sequences-for-hmm-hits -c TM7x.db --list-hmm-sources reported the existence of 61 tRNA genes, the same number as for TM7.

Hey @semiller10, thanks for checking things out. The number of genes reported in `--list-genes` is the number of genes in the anvi'o model, not in the genome you will about the query :) If you run `anvi-run-hmms` on your contigs database the number of genes for Bacteria_71 or Ribosomal_RNAs will not change from genome to genome either :)

So I guess other than this you didn't run into any issue.

Can you check in particular whether you get nucleotide-by-nucleotide accuracy if you use a genome with tRNA gene sequences you know about? I just want to make sure we don't truncate one base from the beginning or the end while parsing the results and cutting sequences.

**Comment by meren** [comment]
> @meren 31 out of the 37 novel archaeal genomes I got here (those with code name LFW_*) have iMet-tRNA. 

Thank you very much for your help, @xvazquezc. I will take a look at the genome you sent sometime tonight and will cover the iMet case.

> Most also have tRNAs with introns, in case you need to check it out.

Stupid evolution :( WHO NEEDS INTRONS IN GODDAM TRNAS?!

Is there anything particular that needs to be done handling them? Anvi'o does not yet know exons/introns (will hopefully learn soon, but I haven't been able to secure time to do that).

**Comment by xvazquezc** [comment]
> Stupid evolution :( WHO NEEDS INTRONS IN GODDAM TRNAS?!

then let's not talk about the genome I have with 20% tRNAs predicted being pseudogenes... 


> Is there anything particular that needs to be done handling them? Anvi'o does not yet know exons/introns (will hopefully learn soon, but I haven't been able to secure time to do that).

Unless Anvi'o uses the coordinates to get sequences or the other way around, it won't probably matter
There will be a discordance between the length parsed from tRNAscan-SE and what you would calculate from the start-stop coordinates.

Columns 7-8 of the tRNAscan-SE output are indeed the coordinates of the introns themselves

**Comment by semiller10** [comment]
> Hey @semiller10, thanks for checking things out. The number of genes reported in --list-genes is the number of genes in the anvi'o model, not in the genome you will about the query

That should have been obvious to me from the number 61, but thanks for clarifying.

I have investigated [E. coli K-12](https://www.ncbi.nlm.nih.gov/nuccore/U00096), which surely has ironclad tRNA gene annotations. tRNAscan predicts the expected number of genes, 87.

Most E. coli tRNA actually has the somewhat odd property of containing 3' CCA within the gene, in contrast to most organisms, which add the acceptor sequence after transcription.

Let's compare the genomic sequences to the sequences reported in `anvi-get-sequences-for-hmm-hits -c Ecoli.db --hmm-source Transfer_RNAs -o trnas.fa`.

[Genomic tRNA-Ile(ATC)](https://www.ncbi.nlm.nih.gov/nuccore/U00096.3?from=225381&to=225457)
77 bases
`1 aggcttgtag ctcaggtggt tagagcgcac ccctgataag ggtgaggtcg gtggttcaag
61 tccactcagg cctacca`

anvio tRNA-Ile(ATC)
76 bases
`>Ile_ATC___Transfer_RNAs___263c84ccd2ff4efbca5370121e484856a09992e06dce48356cf4f79f bin_id:Ecoli|source:Transfer_RNAs|e_value:69.6|contig:c_000000000001|gene_callers_id:4316|start:225381|stop:225457|length:76
GGCTTGTAGCTCAGGTGGTTAGAGCGCACCCCTGATAAGGGTGAGGTCGGTGGTTCAAGTCCACTCAGGCCTACCA`

**The anvio sequence is missing the first nucleotide, A.** Good thing you made sure to check this! This is also seen in the other tRNA species.

**Comment by meren** [comment]
Thanks, @semiller10. It is now fixed.

**Comment by meren** [comment]
Hey @xvazquezc, I've been working on the FASTA file you sent me. I run into a bunch of issues. I realized one of them was due to the fact that when I run tRNAScan-SE on this file the sequences it reports in some cases slightly differs from the tRNA sequences you've sent for it.

Apart from that, I am struggling with how to report the tRNA sequences with introns. Should I slice the intron out, or report something that is not a proper tRNA sequence and lost the intron bounds forever. Neither of them sounds right.

I think what I will do is to report intron bounds in the annotation of the gene in a parsable form in addition what is already there:

image

and then think about whether the program that export sequences should consider those intron bounds to slice them out.

What do you think? Does it sound like a solution to you?

**Comment by xvazquezc** [comment]
> Hey @xvazquezc, I've been working on the FASTA file you sent me. I run into a bunch of issues. I realized one of them was due to the fact that when I run tRNAScan-SE on this file the sequences it reports in some cases slightly differs from the tRNA sequences you've sent for it.

I might have done the original run with the Archaea flag not with the global one like `anvi-scan-trnas` does. So the discrepancies could come from that.


> Apart from that, I am struggling with how to report the tRNA sequences with introns. Should I slice the intron out, or report something that is not a proper tRNA sequence and lost the intron bounds forever. Neither of them sounds right.
> 
> I think what I will do is to report intron bounds in the annotation of the gene in a parsable form in addition what is already there:
> 
> and then think about whether the program that export sequences should consider those intron bounds to slice them out.
> 
> What do you think? Does it sound like a solution to you?

Yeah, I'd report the actual tRNA sequence and keep the intron info in a parsable form wherever you find it more convenient

**Comment by meren** [comment]
> I'd report the actual tRNA sequence and keep the intron info in a parsable form wherever you find it more convenient

Now done that way.

Case without intron:

image

Case with intron:

image

**Comment by meren** [comment]
With the latest commits, `anvi-run-hmms` also scans tRNAs by default, so there is no extra step for tRNA recognition.

That said, `anvi-scan-trnas` is still a separate program dedicated for that task alone, so existing contigs databases can be updated with tRNAs without having to run all HMMs again.

I am merging this to `master` now.

**Comment by meren** [comment]
Thank you very much for your help, @xvazquezc, @semiller10, and @ozcan.

**Pull request merged**
