### PR TITLE
Added quince-mode flag

### PR DESCRIPTION
**Pull request by efogarty11**
We added a quince-mode flag to include sequences with no variability.

### CODE REVIEW

**Comment by meren** [comment]
And it is working without changing anything in the rest of the codebase?

**Comment by efogarty11** [comment]
It appears so 😮

**Comment by meren** [comment]
Is anvi'o magic.

**Comment by meren** [comment]
QUESTION MARK.

**Comment by meren** [comment]
Thank you for taking up on this :)

**Comment by efogarty11** [comment]
> Is anvi'o magic.

It sure seemed like it to Andrea and I. Yay! I'm excited to use it

**Comment by watsonar** [comment]
I'm still upset about how simple this ended up being after I tried to teach myself object oriented programming

but yes, anvi'o is magic.

**Pull request merged**
